### ISSUE TITLE
SplineQueryExecutionListener JsonMappingException: No content to map due to end-of-input

### ISSUE THREAD

**Issue by liangjun-jiang** [AbsaOSS/spline-spark-agent#134]
I am seeing the following exception while running with spark-2.4-spline-agent-bundle_2.12:0.5.5, even though I am seeing the produced json correctly in my endpoint. 

It looks like a serialization issue from Spline model to JSON within spline agent? 

```
20/10/12 11:11:47 ERROR SplineQueryExecutionListener: Unexpected error occurred during lineage processing for application: spark-spline-demo-application #local-1602519094369
com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
 at [Source: ; line: 1, column: 1]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148)
	at com.fasterxml.jackson.databind.ObjectReader._initForReading(ObjectReader.java:381)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1494)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1136)
	at org.json4s.jackson.JsonMethods.parse(JsonMethods.scala:25)
	at org.json4s.jackson.JsonMethods.parse$(JsonMethods.scala:19)
	at __wrapper$1$768939b1afb24a0ea292c637839a0a5b.__wrapper$1$768939b1afb24a0ea292c637839a0a5b$$anon$1.parse(<no source file>)
	at __wrapper$1$e28b5893cc0440a6a78828cb057db8e9.__wrapper$1$e28b5893cc0440a6a78828cb057db8e9$.$anonfun$wrapper$1(<no source file>)
	at za.co.absa.commons.json.AbstractJsonSerDe$JsonToEntity.fromJson(AbstractJsonSerDe.scala:49)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$2(QueryExecutionEventHandler.scala:46)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$2$adapted(QueryExecutionEventHandler.scala:43)
	at scala.Option.foreach(Option.scala:274)
```

This is the spark -submit job I used
```
./bin/spark-submit \
  --packages za.co.absa.spline.agent.spark:spark-2.4-spline-agent-bundle_2.12:0.5.5 \
  --conf "spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener" \
  --conf "spark.spline.producer.url=http://localhost:9090/producer" \
    --class com.expediagroup.datacompute.App \
    --num-executors 1 \
    --driver-memory 512m \
    --executor-memory 512m \
    --executor-cores 1 \
   spark-spline-demo-application-1.0-SNAPSHOT.jar

```
Also this is [the sample app ja](https://github.com/liangjun-jiang/distributed-tracing-in-datahub-with-skywalking/raw/master/screenshots/spark-spline-demo-application-1.0-SNAPSHOT.jar)r file. this sample application converts a bundled `wikidata.csv` to another format.

https://github.com/liangjun-jiang/distributed-tracing-in-datahub-with-skywalking/raw/master/screenshots/spark-spline-demo-application-1.0-SNAPSHOT.jar

**Comment by wajda** [comment]
> ... even though I am seeing the produced json correctly in my endpoint.

Do I understand it correctly that regardless the error the lineage data is still captured and reaches your endpoint?
There has to be two documents produced per job run - an _execution plan_ and an _execution event_

**Comment by liangjun-jiang** [comment]
yes, I am still getting `execution plan`, even with the error information.
for the way I ran the sample project, I didn't receive anything on `execution-events` endpoints.

**Comment by wajda** [comment]
Looking at the [QueryExecutionEventHandler.scala:46](https://github.com/AbsaOSS/spline-spark-agent/blob/develop/core/src/main/scala/za/co/absa/spline/harvester/QueryExecutionEventHandler.scala#L46) I see nothing special but just parsing a a string as _JSON string_ (which is essentially just unquoting).
```scala 
val savedPlanId = UUID.fromString(idAsJson.fromJson[String])
```
Can you debug it and see what value does the `idAsJson` variable contain?
