### ISSUE TITLE
Spline Initialization fails 

### ISSUE THREAD

**Issue by codejoyan** [AbsaOSS/spline-spark-agent#152]
I am trying to enable lineage for one of the spark jobs but the initialization fails with the below error. Please help and let me know what I am missing?

**Error:**
```
20/11/12 14:11:26 ERROR QueryExecutionEventHandlerFactory: Spline initialization failed! Spark Lineage tracking is DISABLED.
java.lang.ClassNotFoundException: za.co.absa.spline.harvester.iwd.DefaultIgnoredWriteDetectionStrategy
```
The spline setup seems to be correct because I am able to see the spline dashboard
http://xx.xx.xxx.xxx:8080/client-web/app/dashboard

Below are the steps I did for enabling the lineage:
1. Added the pom dependency for spline agent.
```xml
<dependency>
    <groupId>za.co.absa.spline.agent.spark</groupId>
    <artifactId>agent-core_2.11</artifactId>
    <version>0.5.5</version>
</dependency>
```
 
2. Enabled Spline Linage by adding below line where spark session is getting initialized
```
SparkLineageInitializer.enableLineageTracking(session);
```
 
3. Add JVM below JVM Arguments. Can be governed by Automic env param and put in a generic shell. Alternatively, you can add “spline.properties” to “src/main/resoruces”. I have attached one with Prod end point enabled
 ```
spline.mode=BEST_EFFORT
#UAT
spline.producer.url=http://xx.xx.xxx.xxx:8080/rest-gateway/producer
```
**Detailed Stacktrace:**
```
20/11/12 14:11:26 ERROR QueryExecutionEventHandlerFactory: Spline initialization failed! Spark Lineage tracking is DISABLED.
java.lang.ClassNotFoundException: za.co.absa.spline.harvester.iwd.DefaultIgnoredWriteDetectionStrategy
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.instantiate(DefaultSplineConfigurer.scala:112)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.ignoredWriteDetectionStrategy(DefaultSplineConfigurer.scala:95)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.harvesterFactory(DefaultSplineConfigurer.scala:104)
	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.queryExecutionEventHandler(DefaultSplineConfigurer.scala:90)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$$initEventHandler(QueryExecutionEventHandlerFactory.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$1$$anonfun$apply$1.apply(QueryExecutionEventHandlerFactory.scala:46)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$1$$anonfun$apply$1.apply(QueryExecutionEventHandlerFactory.scala:46)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$$assureOneListenerPerSession(QueryExecutionEventHandlerFactory.scala:78)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$1.apply(QueryExecutionEventHandlerFactory.scala:45)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$1.apply(QueryExecutionEventHandlerFactory.scala:42)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.withErrorHandling(QueryExecutionEventHandlerFactory.scala:55)
	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.createEventHandler(QueryExecutionEventHandlerFactory.scala:41)
	at za.co.absa.spline.harvester.SparkLineageInitializer$SparkSessionWrapper.enableLineageTracking(SparkLineageInitializer.scala:49)
	at za.co.absa.spline.harvester.SparkLineageInitializer$.enableLineageTracking(SparkLineageInitializer.scala:32)
	at 
```

**Comment by wajda** [comment]
```
java.lang.ClassNotFoundException: za.co.absa.spline.harvester.iwd.DefaultIgnoredWriteDetectionStrategy
```
That's interesting. The class is a part of `agent-core.jar`, the same jar that contains the other `za.co.absa.spline.harvester.*` classes. So why wouldn't it find `DefaultIgnoredWriteDetectionStrategy` when it finds the others?
As I understand you are using Spline agent core as a dependency to build your own fat jar.
Do you apply any sort of class filtering, shading or class renaming in your build process?
Please check your resulted fat jar and make sure the aforementioned class is physically there.

**Comment by codejoyan** [comment]
Yes, I am building a fat jar. I do have filtering in the build process but I could not find any position to filter out these classes.
Also, as you said the aforementioned class is absent in the resultant fat jar. I am cross-checking if the build process is causing this. Thanks. Any other points I might be missing

$ jar tf XXXXXXXXX-1.0.20-SNAPSHOT-fat.jar|grep za.co.absa.spline.harvester.iwd
za/co/absa/spline/harvester/iwd/
za/co/absa/spline/harvester/iwd/IgnoredWriteDetectionStrategy.class

**Comment by codejoyan** [comment]
This issue was due to few configurations in the build process. After removing these in the pom.xml the resultant jar had all the necessary class files and we were able to see the lineage generated.

<minimizeJar>true</minimizeJar>
<shadedArtifactAttached>true</shadedArtifactAttached>

**Comment by Venky-mca** [comment]
@codejoyan @wajda 
I'm also getting the same issue in my fat jar I don't have DefaultIgnoredWriteDetectionStrategy. I only had IgnoredWriteDetectionStrategy

Please help me what to do
