### ISSUE TITLE
Spline config to support more dispatcher types

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#165]
To accommodate for multi-dispatcher setups, we need to change the Spline config schema such that different dispatchers' properties are defined in their own namespace and do not collide with others.

Example:
```properties

# Means Spline will use "composite" dispatcher to dispatch lineage data.
# Here "composite" is a logical dispatcher name, one of those that are configured below.
spline.dispatcher=composite

# Below we configure individual dispatchers.
# The property name pattern is always "spline.dispatcher.xxx.a.b.c.d",
# where "xxx" is the logical name of the dispatcher, and "a.b.c.d" is an arbitrary property for that particular dispatcher.

# "composite" dispatcher config
spline.dispatcher.composite.className=...
# sets a list of child dispatchers' names to delegate to
spline.dispatcher.composite.dispatchers=http,kafka

# "http" dispatcher config
spline.dispatcher.http.className=za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher
spline.dispatcher.http.producer.url=...

# "kafka" dispatcher config
spline.dispatcher.kafka.className=za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher
spline.dispatcher.kafka.topic.execPlans=
spline.dispatcher.kafka.topic.execEvents=
```

**Comment by wajda** [comment]
Tip: Apache Configuration utils might come in handy for dealing with property namespaces.

```java
package org.apache.commons.configuration

...

public interface Configuration
{
    /**
     * Return a decorator Configuration containing every key from the current
     * Configuration that starts with the specified prefix. The prefix is
     * removed from the keys in the subset. For example, if the configuration
     * contains the following properties:
     *
     * <pre>
     *    prefix.number = 1
     *    prefix.string = Apache
     *    prefixed.foo = bar
     *    prefix = Jakarta
     * </pre>
     *
     * the Configuration returned by {@code subset("prefix")} will contain
     * the properties:
     *
     * <pre>
     *    number = 1
     *    string = Apache
     *    = Jakarta
     * </pre>
     *
     * (The key for the value "Jakarta" is an empty string)
     * <p>
     * Since the subset is a decorator and not a modified copy of the initial
     * Configuration, any change made to the subset is available to the
     * Configuration, and reciprocally.
     *
     * @param prefix The prefix used to select the properties.
     * @return a subset configuration
     *
     * @see SubsetConfiguration
     */
    Configuration subset(String prefix);

    ...
```

**Comment by wajda** [comment]
Looks like something is wrong with 05 config adapter.
Getting this exception when running examples with all defaults (that are set in old config - see `examples/run-example.xml`).
```
[java] 21/02/05 00:26:43 ERROR QueryExecutionEventHandlerFactory: Spline initialization failed! Spark Lineage tracking is DISABLED.
     [java] java.lang.IllegalArgumentException: Missing configuration property producer.url
     [java] 	at za.co.absa.commons.config.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$za$co$absa$commons$config$ConfigurationImplicits$ConfigurationRequiredWrapper$$getRequired$extension$2.apply(ConfigurationImplicits.scala:110)
     [java] 	at za.co.absa.commons.config.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$za$co$absa$commons$config$ConfigurationImplicits$ConfigurationRequiredWrapper$$getRequired$extension$2.apply(ConfigurationImplicits.scala:110)
     [java] 	at scala.util.Try.getOrElse(Try.scala:79)
     [java] 	at za.co.absa.commons.config.ConfigurationImplicits$ConfigurationRequiredWrapper$.za$co$absa$commons$config$ConfigurationImplicits$ConfigurationRequiredWrapper$$getRequired$extension(ConfigurationImplicits.scala:110)
     [java] 	at za.co.absa.commons.config.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$extension$3.apply(ConfigurationImplicits.scala:42)
     [java] 	at za.co.absa.commons.config.ConfigurationImplicits$ConfigurationRequiredWrapper$$anonfun$getRequiredString$extension$3.apply(ConfigurationImplicits.scala:42)
     [java] 	at za.co.absa.spline.harvester.dispatcher.httpdispatcher.HttpLineageDispatcherConfig.<init>(HttpLineageDispatcherConfig.scala:37)
     [java] 	at za.co.absa.spline.harvester.dispatcher.httpdispatcher.HttpLineageDispatcherConfig$.apply(HttpLineageDispatcherConfig.scala:33)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$createDefaultRestClient(HttpLineageDispatcher.scala:95)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.<init>(HttpLineageDispatcher.scala:46)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.instantiate(DefaultSplineConfigurer.scala:136)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.lineageDispatcher(DefaultSplineConfigurer.scala:101)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.queryExecutionEventHandler(DefaultSplineConfigurer.scala:96)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$$initEventHandler(QueryExecutionEventHandlerFactory.scala:64)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6$$anonfun$apply$1.apply(QueryExecutionEventHandlerFactory.scala:46)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6$$anonfun$apply$1.apply(QueryExecutionEventHandlerFactory.scala:46)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$$assureOneListenerPerSession(QueryExecutionEventHandlerFactory.scala:78)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:45)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:42)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.withErrorHandling(QueryExecutionEventHandlerFactory.scala:55)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.createEventHandler(QueryExecutionEventHandlerFactory.scala:41)
     [java] 	at za.co.absa.spline.harvester.SparkLineageInitializer$SparkSessionWrapper.enableLineageTracking(SparkLineageInitializer.scala:49)
     [java] 	at za.co.absa.spline.example.batch.Example1Job$.delayedEndpoint$za$co$absa$spline$example$batch$Example1Job$1(Example1Job.scala:26)
     [java] 	at za.co.absa.spline.example.batch.Example1Job$delayedInit$body.apply(Example1Job.scala:23)
     [java] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
     [java] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
     [java] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java] 	at scala.collection.immutable.List.foreach(List.scala:392)
     [java] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
     [java] 	at scala.App$class.main(App.scala:76)
     [java] 	at za.co.absa.spline.SparkApp.main(SparkApp.scala:27)
     [java] 	at za.co.absa.spline.example.batch.Example1Job.main(Example1Job.scala)
```
