### ISSUE TITLE
Unable to run example docker image

### ISSUE THREAD

**Issue by bensenberner** [AbsaOSS/spline-spark-agent#235]
Steps to reproduce:
```
$ docker run -p 8529:8529 -e ARANGO_NO_AUTH=1 arangodb/arangodb:3.7.10  # start running arango
$ docker run -it --rm absaoss/spline-admin:0.6.0 db-init -k arangodb://172.17.0.1:8529/spline # initialize the spline database
$ docker container run \
  -e SPLINE_DATABASE_CONNECTION_URL=arangodb://host.docker.internal/spline \
  -p 8080:8080 \
  absaoss/spline-rest-server:0.6.0 # start the spline server, connect to the arango db
$ git clone git@github.com:AbsaOSS/spline-spark-agent.git
$ cd spline-spark-agent
$ mvn install -DskipTests
$ docker build -f Dockerfile . -t spline-spark-agent-examples:v0.1.1
$ docker run -e "SPLINE_PRODUCER_URL=http://localhost:8080/producer" spline-spark-agent-examples:v0.1.1
```

output:
```
[INFO] Scanning for projects...
[INFO]
[INFO] ------------< za.co.absa.spline.agent.spark:examples_2.11 >-------------
[INFO] Building examples_2.11 0.7.0-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ examples_2.11 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO]
[INFO] --- scala-maven-plugin:4.2.0:add-source (scala-compile) @ examples_2.11 ---
[INFO] Add Source directory: /opt/spline-spark-agent/examples/src/main/scala
[INFO] Add Test Source directory: /opt/spline-spark-agent/examples/src/test/scala
[INFO]
[INFO] --- scala-maven-plugin:4.2.0:compile (scala-compile) @ examples_2.11 ---
[INFO] Using incremental compilation using Mixed compile order
[INFO] compile in 5.2 s
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ examples_2.11 ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 1 source file to /opt/spline-spark-agent/examples/target/classes
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ examples_2.11 ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /opt/spline-spark-agent/examples/src/test/resources
[INFO]
[INFO] --- scala-maven-plugin:4.2.0:testCompile (scala-test-compile) @ examples_2.11 ---
[INFO] compile in 0.0 s
[INFO] No sources to compile
[INFO]
[INFO] --- maven-compiler-plugin:3.8.1:testCompile (default-testCompile) @ examples_2.11 ---
[INFO] No sources to compile
[INFO]
[INFO] --- maven-surefire-plugin:2.22.2:test (default-test) @ examples_2.11 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- scalatest-maven-plugin:2.0.1:test (test) @ examples_2.11 ---
[INFO] Tests are skipped.
[INFO]
[INFO] --- maven-antrun-plugin:1.8:run (default) @ examples_2.11 ---
[INFO] Executing tasks

main:

main:

runAll:
  [foreach] The nested fileset element is deprectated, use a nested path instead

runFile:

runClass:
     [echo] Running za.co.absa.spline.example.batch.CodelessInitExampleJob
[echoproperties] #Ant properties
[echoproperties] #Fri Jun 04 16:01:47 UTC 2021
[echoproperties] http.nonProxyHosts=
[echoproperties] http.proxyHost=
[echoproperties] http.proxyPort=
[echoproperties] spline.mode=REQUIRED
[echoproperties] spline.producer.url=http\://localhost\:8080/producer
     [java] Using Spark's default log4j profile: org/apache/spark/log4j-defaults.properties
     [java] 21/06/04 16:01:49 INFO SparkContext: Running Spark version 2.4.2
     [java] 21/06/04 16:01:49 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
     [java] 21/06/04 16:01:50 INFO SparkContext: Submitted application: Codeless Init Example Job
     [java] 21/06/04 16:01:50 INFO SecurityManager: Changing view acls to: root
     [java] 21/06/04 16:01:50 INFO SecurityManager: Changing modify acls to: root
     [java] 21/06/04 16:01:50 INFO SecurityManager: Changing view acls groups to:
     [java] 21/06/04 16:01:50 INFO SecurityManager: Changing modify acls groups to:
     [java] 21/06/04 16:01:50 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users  with view permissions: Set(root); groups with view permissions: Set(); users  with modify permissions: Set(root); groups with modify permissions: Set()
     [java] 21/06/04 16:01:50 INFO Utils: Successfully started service 'sparkDriver' on port 40961.
     [java] 21/06/04 16:01:50 INFO SparkEnv: Registering MapOutputTracker
     [java] 21/06/04 16:01:50 INFO SparkEnv: Registering BlockManagerMaster
     [java] 21/06/04 16:01:50 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
     [java] 21/06/04 16:01:50 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
     [java] 21/06/04 16:01:51 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-3c7ecb75-9a0b-4b98-9f29-bda6fd35a307
     [java] 21/06/04 16:01:51 INFO MemoryStore: MemoryStore started with capacity 379.2 MB
     [java] 21/06/04 16:01:51 INFO SparkEnv: Registering OutputCommitCoordinator
     [java] 21/06/04 16:01:51 INFO Utils: Successfully started service 'SparkUI' on port 4040.
     [java] 21/06/04 16:01:51 INFO SparkUI: Bound SparkUI to 0.0.0.0, and started at http://dc0b6828604e:4040
     [java] 21/06/04 16:01:51 INFO Executor: Starting executor ID driver on host localhost
     [java] 21/06/04 16:01:51 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40649.
     [java] 21/06/04 16:01:51 INFO NettyBlockTransferService: Server created on dc0b6828604e:40649
     [java] 21/06/04 16:01:51 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
     [java] 21/06/04 16:01:51 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, dc0b6828604e, 40649, None)
     [java] 21/06/04 16:01:51 INFO BlockManagerMasterEndpoint: Registering block manager dc0b6828604e:40649 with 379.2 MB RAM, BlockManagerId(driver, dc0b6828604e, 40649, None)
     [java] 21/06/04 16:01:51 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, dc0b6828604e, 40649, None)
     [java] 21/06/04 16:01:51 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, dc0b6828604e, 40649, None)
     [java] 21/06/04 16:01:52 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir ('file:/opt/spline-spark-agent/examples/spark-warehouse').
     [java] 21/06/04 16:01:52 INFO SharedState: Warehouse path is 'file:/opt/spline-spark-agent/examples/spark-warehouse'.
     [java] 21/06/04 16:01:53 INFO StateStoreCoordinatorRef: Registered StateStoreCoordinator endpoint
     [java] 21/06/04 16:01:53 INFO QueryExecutionEventHandlerFactory: Initializing Spline agent...
     [java] 21/06/04 16:01:53 INFO QueryExecutionEventHandlerFactory: Spline init type: AUTO (codeless)
     [java] 21/06/04 16:01:54 INFO QueryExecutionEventHandlerFactory: Spline version: 0.7.0-SNAPSHOT (rev. b391bae)
     [java] 21/06/04 16:01:54 INFO QueryExecutionEventHandlerFactory: Spline mode: REQUIRED
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.AvroPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CassandraPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CobrixPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.DatabricksPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ElasticSearchPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ExcelPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.JDBCPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.KafkaPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.MongoPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.SQLPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.XMLPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.composite.LogicalRelationPlugin
     [java] 21/06/04 16:02:13 INFO AutoDiscoveryPluginRegistry: Loading plugin: class za.co.absa.spline.harvester.plugin.composite.SaveIntoDataSourceCommandPlugin
     [java] 21/06/04 16:02:13 INFO HttpLineageDispatcher: Producer URL: http://localhost:8080/producer
     [java] Exception in thread "main" java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.internal.SessionStateBuilder':
     [java] 	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1107)
     [java] 	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:145)
     [java] 	at org.apache.spark.sql.SparkSession$$anonfun$sessionState$2.apply(SparkSession.scala:144)
     [java] 	at scala.Option.getOrElse(Option.scala:121)
     [java] 	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:144)
     [java] 	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:141)
     [java] 	at org.apache.spark.sql.DataFrameReader.<init>(DataFrameReader.scala:785)
     [java] 	at org.apache.spark.sql.SparkSession.read(SparkSession.scala:655)
     [java] 	at za.co.absa.spline.example.batch.CodelessInitExampleJob$.delayedEndpoint$za$co$absa$spline$example$batch$CodelessInitExampleJob$1(CodelessInitExampleJob.scala:31)
     [java] 	at za.co.absa.spline.example.batch.CodelessInitExampleJob$delayedInit$body.apply(CodelessInitExampleJob.scala:25)
     [java] 	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
     [java] 	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
     [java] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java] 	at scala.App$$anonfun$main$1.apply(App.scala:76)
     [java] 	at scala.collection.immutable.List.foreach(List.scala:392)
     [java] 	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
     [java] 	at scala.App$class.main(App.scala:76)
     [java] 	at za.co.absa.spline.SparkApp.main(SparkApp.scala:27)
     [java] 	at za.co.absa.spline.example.batch.CodelessInitExampleJob.main(CodelessInitExampleJob.scala)
     [java] Caused by: za.co.absa.spline.harvester.exception.SplineInitializationException: Spark Agent was not able to establish connection to Spline Gateway
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders$1.applyOrElse(HttpLineageDispatcher.scala:118)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders$1.applyOrElse(HttpLineageDispatcher.scala:116)
     [java] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
     [java] 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
     [java] 	at scala.util.Try$.apply(Try.scala:192)
     [java] 	at scala.util.Failure.recover(Try.scala:216)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders(HttpLineageDispatcher.scala:116)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.<init>(HttpLineageDispatcher.scala:50)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.<init>(HttpLineageDispatcher.scala:45)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     [java] 	at za.co.absa.commons.HierarchicalObjectFactory$$anonfun$instantiate$1.applyOrElse(HierarchicalObjectFactory.scala:43)
     [java] 	at za.co.absa.commons.HierarchicalObjectFactory$$anonfun$instantiate$1.applyOrElse(HierarchicalObjectFactory.scala:42)
     [java] 	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
     [java] 	at scala.util.Failure$$anonfun$recover$1.apply(Try.scala:216)
     [java] 	at scala.util.Try$.apply(Try.scala:192)
     [java] 	at scala.util.Failure.recover(Try.scala:216)
     [java] 	at za.co.absa.commons.HierarchicalObjectFactory.instantiate(HierarchicalObjectFactory.scala:42)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.createComponentByKey(DefaultSplineConfigurer.scala:115)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.lineageDispatcher(DefaultSplineConfigurer.scala:99)
     [java] 	at za.co.absa.spline.harvester.conf.DefaultSplineConfigurer.queryExecutionEventHandler(DefaultSplineConfigurer.scala:97)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.za$co$absa$spline$harvester$QueryExecutionEventHandlerFactory$$initEventHandler(QueryExecutionEventHandlerFactory.scala:64)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:43)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory$$anonfun$createEventHandler$6.apply(QueryExecutionEventHandlerFactory.scala:42)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.withErrorHandling(QueryExecutionEventHandlerFactory.scala:55)
     [java] 	at za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory.createEventHandler(QueryExecutionEventHandlerFactory.scala:41)
     [java] 	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$.za$co$absa$spline$harvester$listener$SplineQueryExecutionListener$$constructEventHandler(SplineQueryExecutionListener.scala:67)
     [java] 	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.<init>(SplineQueryExecutionListener.scala:37)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
     [java] 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
     [java] 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
     [java] 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
     [java] 	at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2691)
     [java] 	at org.apache.spark.util.Utils$$anonfun$loadExtensions$1.apply(Utils.scala:2680)
     [java] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
     [java] 	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
     [java] 	at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
     [java] 	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:48)
     [java] 	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
     [java] 	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)
     [java] 	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:2680)
     [java] 	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$$lessinit$greater$1.apply(QueryExecutionListener.scala:83)
     [java] 	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$$lessinit$greater$1.apply(QueryExecutionListener.scala:82)
     [java] 	at scala.Option.foreach(Option.scala:257)
     [java] 	at org.apache.spark.sql.util.ExecutionListenerManager.<init>(QueryExecutionListener.scala:82)
     [java] 	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$listenerManager$2.apply(BaseSessionStateBuilder.scala:270)
     [java] 	at org.apache.spark.sql.internal.BaseSessionStateBuilder$$anonfun$listenerManager$2.apply(BaseSessionStateBuilder.scala:270)
     [java] 	at scala.Option.getOrElse(Option.scala:121)
     [java] 	at org.apache.spark.sql.internal.BaseSessionStateBuilder.listenerManager(BaseSessionStateBuilder.scala:269)
     [java] 	at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:297)
     [java] 	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1104)
     [java] 	... 18 more
     [java] Caused by: java.net.ConnectException: Connection refused (Connection refused)
     [java] 	at java.net.PlainSocketImpl.socketConnect(Native Method)
     [java] 	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
     [java] 	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
     [java] 	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
     [java] 	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
     [java] 	at java.net.Socket.connect(Socket.java:607)
     [java] 	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
     [java] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
     [java] 	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
     [java] 	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
     [java] 	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
     [java] 	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1570)
     [java] 	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
     [java] 	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
     [java] 	at scalaj.http.HttpRequest.scalaj$http$HttpRequest$$doConnection(Http.scala:367)
     [java] 	at scalaj.http.HttpRequest.exec(Http.scala:343)
     [java] 	at scalaj.http.HttpRequest.asString(Http.scala:491)
     [java] 	at za.co.absa.spline.harvester.dispatcher.httpdispatcher.rest.RestEndpoint.head(RestEndpoint.scala:33)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders$2.apply(HttpLineageDispatcher.scala:107)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders$2.apply(HttpLineageDispatcher.scala:107)
     [java] 	at scala.util.Try$.apply(Try.scala:192)
     [java] 	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$getServerHeaders(HttpLineageDispatcher.scala:107)
     [java] 	... 64 more
     [java] 21/06/04 16:02:13 INFO SparkContext: Invoking stop() from shutdown hook
     [java] 21/06/04 16:02:14 INFO SparkUI: Stopped Spark web UI at http://dc0b6828604e:4040
     [java] 21/06/04 16:02:14 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
     [java] 21/06/04 16:02:15 INFO MemoryStore: MemoryStore cleared
     [java] 21/06/04 16:02:15 INFO BlockManager: BlockManager stopped
     [java] 21/06/04 16:02:15 INFO BlockManagerMaster: BlockManagerMaster stopped
     [java] 21/06/04 16:02:15 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
     [java] 21/06/04 16:02:15 INFO SparkContext: Successfully stopped SparkContext
     [java] 21/06/04 16:02:15 INFO ShutdownHookManager: Shutdown hook called
     [java] 21/06/04 16:02:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-6269820f-1ae3-403b-a6f7-f3223537e030
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  39.514 s
[INFO] Finished at: 2021-06-04T16:02:15Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-antrun-plugin:1.8:run (default) on project examples_2.11: An Ant BuildException has occured: The following error occurred while executing this line:
[ERROR] /opt/spline-spark-agent/examples/run-example.xml:42: The following error occurred while executing this line:
[ERROR] /opt/spline-spark-agent/examples/run-example.xml:48: The following error occurred while executing this line:
[ERROR] /opt/spline-spark-agent/examples/run-example.xml:66: The following error occurred while executing this line:
[ERROR] /opt/spline-spark-agent/examples/run-example.xml:98: Java returned: 1
[ERROR] around Ant part ...<ant antfile="/opt/spline-spark-agent/examples/run-example.xml">... @ 5:67 in /opt/spline-spark-agent/examples/target/antrun/build-main.xml
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by wajda** [comment]
I think the error message is clear:
```
     [java] 21/06/04 16:02:13 INFO HttpLineageDispatcher: Producer URL: http://localhost:8080/producer
     [java] Caused by: za.co.absa.spline.harvester.exception.SplineInitializationException: Spark Agent was not able to establish connection to Spline Gateway
     [java] Caused by: java.net.ConnectException: Connection refused (Connection refused)
```
You have to use a host name / IP that is accessible from the inside the docker container.
