### ISSUE TITLE
Attempting to codeless initialisation causes Databricks cluster to Terminate

### ISSUE THREAD

**Issue by KeyboardMonkey221** [AbsaOSS/spline-spark-agent#263]
My goal is to implement a similar cloud structure as https://intellishore.dk/data-lineage-from-databricks-to-azure-purview/ though with the latest versions of spline and using codeless initialization.

Unfortunately, each time I try to configure the cluster with spark configuration, the cluster terminates with the following error log.

```
java.lang.IllegalArgumentException: Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1204)
	at org.apache.spark.sql.SparkSession.$anonfun$sessionState$2(SparkSession.scala:195)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.SparkSession.sessionState$lzycompute(SparkSession.scala:193)
	at org.apache.spark.sql.SparkSession.sessionState(SparkSession.scala:190)
	at org.apache.spark.sql.SparkSession.streams(SparkSession.scala:282)
	at org.apache.spark.sql.SQLContext.streams(SQLContext.scala:718)
	at com.databricks.backend.daemon.driver.DatabricksStreamingQueryListener.<init>(DatabricksStreamingQueryListener.scala:53)
	at com.databricks.backend.daemon.driver.DriverSparkHooks.<init>(DriverSparkHooks.scala:30)
	at com.databricks.backend.daemon.driver.DriverCorral.<init>(DriverCorral.scala:247)
	at com.databricks.backend.daemon.driver.DriverDaemon.<init>(DriverDaemon.scala:39)
	at com.databricks.backend.daemon.driver.DriverDaemon$.create(DriverDaemon.scala:211)
	at com.databricks.backend.daemon.driver.DriverDaemon$.wrappedMain(DriverDaemon.scala:216)
	at com.databricks.DatabricksMain.$anonfun$main$1(DatabricksMain.scala:106)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.DatabricksMain.$anonfun$withStartupProfilingData$1(DatabricksMain.scala:321)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$4(UsageLogging.scala:431)
	at com.databricks.logging.UsageLogging.$anonfun$withAttributionContext$1(UsageLogging.scala:239)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:234)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:231)
	at com.databricks.DatabricksMain.withAttributionContext(DatabricksMain.scala:74)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:276)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:269)
	at com.databricks.DatabricksMain.withAttributionTags(DatabricksMain.scala:74)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:412)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:338)
	at com.databricks.DatabricksMain.recordOperation(DatabricksMain.scala:74)
	at com.databricks.DatabricksMain.withStartupProfilingData(DatabricksMain.scala:321)
	at com.databricks.DatabricksMain.main(DatabricksMain.scala:105)
	at com.databricks.backend.daemon.driver.DriverDaemon.main(DriverDaemon.scala)
Caused by: java.lang.ClassNotFoundException: za.co.absa.spline.harvester.listener.SplineQueryExecutionListener
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.spark.util.Utils$.classForName(Utils.scala:226)
	at org.apache.spark.util.Utils$.$anonfun$loadExtensions$1(Utils.scala:3006)
	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
	at org.apache.spark.util.Utils$.loadExtensions(Utils.scala:3004)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$new$2(QueryExecutionListener.scala:88)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$new$2$adapted(QueryExecutionListener.scala:87)
	at scala.Option.foreach(Option.scala:407)
	at org.apache.spark.sql.util.ExecutionListenerManager.<init>(QueryExecutionListener.scala:87)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.$anonfun$listenerManager$2(BaseSessionStateBuilder.scala:329)
	at scala.Option.getOrElse(Option.scala:189)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.listenerManager(BaseSessionStateBuilder.scala:329)
	at org.apache.spark.sql.internal.BaseSessionStateBuilder.build(BaseSessionStateBuilder.scala:356)
	at org.apache.spark.sql.SparkSession$.org$apache$spark$sql$SparkSession$$instantiateSessionState(SparkSession.scala:1201)
	... 30 more
21/06/30 06:44:05 INFO SparkContext: Invoking stop() from shutdown hook
```

Here is a description of my setup:

- spline .jar file
     - I'm using a `spark-3.0-spline-agent-bundle_2.12-0.6.1.jar` file
     - I built it by using a Dockerfile like the following and executing `mvn package` in the 3.0 agent folder, and then copy it over onto my local machine
          - note: I'm not experienced with maven (couldn't get it to build on my machine, so I figured I'd hand maven configuration to the docker image instead)
``` Dockerfile
FROM absaoss/spline-spark-agent
ENTRYPOINT ["/bin/bash"]
```

- Databrick cluster
     - Using 7.3 Databricks runtime (Spark 3.0.1 and Scala 2.12)
     - The spark configuration is
```
spark.sql.queryExecutionListeners za.co.absa.spline.harvester.listener.SplineQueryExecutionListener
spark.spline.lineageDispatcher.http.producer.url https://requestbin.net/r/xxxxxxx
spark.databricks.cluster.profile serverless
spark.databricks.repl.allowedLanguages sql,python,r
```

Note, I'm using requestbin just cause I want to see SOMETHING before I hook it up into an azure function.

I've also tried going into the Databrick library and getting the jar content from a Maven Package via the options menu.

Please help, I'm not sure why it can't find the correct Class, `SplineQueryExecutionListener`

**Comment by cerveada** [comment]
`spark-3.0-spline-agent-bundle_2.12-0.6.1.jar` is ready to use bundle, you don't need to build anything it is available here:
https://mvnrepository.com/artifact/za.co.absa.spline.agent.spark/spark-3.0-spline-agent-bundle_2.12/0.6.1

The bundle jar file must be on a class path for spark to be able to initialize the agent. Docker will not help with this. 

Now to put the jar on a classpath in a normal Spark you just use `--packages` flag with Maven coordinates. This may be not possible to do on Databricks, but here is a guide how to do it there:

https://databricks.com/blog/2015/07/28/using-3rd-party-libraries-in-databricks-apache-spark-packages-and-maven-libraries.html

**Comment by wajda** [comment]
@KeyboardMonkey221, that is Databricks issue - it loads libraries too late, making codeless init impossible.

Please refer this Hiw-To draft - https://github.com/AbsaOSS/spline-getting-started/blob/feature/spline-getting-started-5/spline-on-databricks/README.md

**Comment by KeyboardMonkey221** [comment]
Perfect - thank you for the tip @cerveada for the maven package, and thank you for explaining why it doesn't work on Databricks @wajda.

Things are resolved on my end with this issue.

**Comment by ganeshnikumbh** [comment]
@KeyboardMonkey221 @wajda @cerveada , if this is still a issue please refer to #409 where I have mentioned how to do codeless initialization. If you have also look into the other issue mentioned there, then that would be a great benefit for us all.
