### ISSUE TITLE
At least one operation defines output schema [#2], while some terminal input operations lack of it [#3]

### ISSUE THREAD

**Issue by rsaw4** [AbsaOSS/spline-spark-agent#264]
using spark-2.4-spline-agent-bundle_2.11-0.6.1.jar, spark 2.4, spline ui and rest-server 0.6, arangodb:3.7.10. spline components using docker quickstart
```
2021-07-02 00:42:32,977 [main] INFO  com.yotpo.metorikku.Metorikku$ - Starting Metorikku - Parsing configuration
2021-07-02 00:42:33,069 [main] INFO  com.yotpo.metorikku.configuration.job.ConfigurationParser$ - Starting Metorikku - Parsing configuration
2021-07-02 00:42:34,766 [main] INFO  za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory - Initializing Spline agent...
2021-07-02 00:42:34,767 [main] INFO  za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory - Spline init type: AUTO (codeless)
2021-07-02 00:42:34,773 [main] INFO  za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory - Spline version: 0.6.1 (rev. 0bd860a)
2021-07-02 00:42:34,789 [main] INFO  za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory - Spline mode: REQUIRED
2021-07-02 00:42:34,791 [main] INFO  za.co.absa.spline.harvester.conf.DefaultSplineConfigurer - Lineage Dispatcher: http
2021-07-02 00:42:34,791 [main] INFO  za.co.absa.spline.harvester.conf.DefaultSplineConfigurer - Post-Processing Filter: composite
2021-07-02 00:42:34,792 [main] INFO  za.co.absa.spline.harvester.conf.DefaultSplineConfigurer - Ignore-Write Detection Strategy: default
2021-07-02 00:42:44,347 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.AvroPlugin
2021-07-02 00:42:44,349 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CassandraPlugin
2021-07-02 00:42:44,350 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.CobrixPlugin
2021-07-02 00:42:44,351 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.DatabricksPlugin
2021-07-02 00:42:44,357 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ElasticSearchPlugin
2021-07-02 00:42:44,358 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.ExcelPlugin
2021-07-02 00:42:44,358 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.JDBCPlugin
2021-07-02 00:42:44,360 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.KafkaPlugin
2021-07-02 00:42:44,360 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.MongoPlugin
2021-07-02 00:42:44,360 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.SQLPlugin
2021-07-02 00:42:44,362 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.embedded.XMLPlugin
2021-07-02 00:42:44,363 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.composite.LogicalRelationPlugin
2021-07-02 00:42:44,363 [main] INFO  za.co.absa.spline.harvester.plugin.registry.AutoDiscoveryPluginRegistry - Loading plugin: class za.co.absa.spline.harvester.plugin.composite.SaveIntoDataSourceCommandPlugin
2021-07-02 00:42:44,373 [main] INFO  za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher - Producer URL: http://redac:8080/producer
2021-07-02 00:42:44,458 [main] INFO  za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher - Using Producer API version: 1.1
2021-07-02 00:42:44,460 [main] INFO  za.co.absa.spline.harvester.QueryExecutionEventHandlerFactory - Spline successfully initialized. Spark Lineage tracking is ENABLED.
2021-07-02 00:42:44,986 [main] WARN  org.apache.spark.sql.SparkSession$Builder - Using an existing SparkSession; some spark core configurations may not take effect.
2021-07-02 00:42:44,991 [main] INFO  com.yotpo.metorikku.instrumentation.StreamingQueryMetricsListener$ - Initialize stream listener
2021-07-02 00:42:48,258 [main] INFO  com.yotpo.metorikku.metric.MetricSet - Starting to parse metricSet
2021-07-02 00:42:48,262 [main] INFO  com.yotpo.metorikku.configuration.metric.ConfigurationParser$ - Initializing Metric file cgmspark_ingest_batch_start_metric.yaml
2021-07-02 00:42:48,380 [main] INFO  com.yotpo.metorikku.metric.Metric - Calculating step batch_status
2021-07-02 00:42:50,719 [main] INFO  com.yotpo.metorikku.metric.Metric - Starting to Write results of batch_status
2021-07-02 00:42:50,724 [main] INFO  com.yotpo.metorikku.output.writers.file.FileOutputWriter - Writing file to s3a://redacus
2021-07-02 00:42:51,692 [Executor task launch worker for task 2] INFO  org.apache.parquet.hadoop.InternalParquetRecordWriter - Flushing mem columnStore to file. allocated memory: 100
2021-07-02 00:43:03,093 [main] ERROR za.co.absa.spline.harvester.listener.SplineQueryExecutionListener - Unexpected error occurred during lineage processing for application: lin1 #local-1625186553867
java.lang.RuntimeException: Cannot send lineage data to http://redac:8080/producer/execution-plans. HTTP Response: 400 Inconsistent entity: At least one operation defines output schema [#2], while some terminal input operations lack of it [#3]
        at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.sendJson(HttpLineageDispatcher.scala:83)
        at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.send(HttpLineageDispatcher.scala:60)
        at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$2.apply(QueryExecutionEventHandler.scala:45)
        at za.co.absa.spline.harvester.QueryExecutionEventHandler$$anonfun$onSuccess$2.apply(QueryExecutionEventHandler.scala:43)
        at scala.Option.foreach(Option.scala:257)
        at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:43)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(SplineQueryExecutionListener.scala:40)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(SplineQueryExecutionListener.scala:40)
        at scala.Option.foreach(Option.scala:257)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener$$anonfun$onSuccess$1.apply$mcV$sp(SplineQueryExecutionListener.scala:40)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
        at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:39)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:129)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:157)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:155)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
        at org.apache.spark.sql.util.ExecutionListenerManager.org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling(QueryExecutionListener.scala:155)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply$mcV$sp(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:128)
        at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:168)
        at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:127)
        at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:679)
        at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:286)
        at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:272)
        at com.yotpo.metorikku.output.writers.file.FileOutputWriter.save(FileOutputWriter.scala:106)
        at com.yotpo.metorikku.output.writers.file.FileOutputWriter.write(FileOutputWriter.scala:76)
        at com.yotpo.metorikku.metric.Metric.com$yotpo$metorikku$metric$Metric$$writeBatch(Metric.scala:102)
        at com.yotpo.metorikku.metric.Metric$$anonfun$write$1.apply(Metric.scala:156)
        at com.yotpo.metorikku.metric.Metric$$anonfun$write$1.apply(Metric.scala:134)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.yotpo.metorikku.metric.Metric.write(Metric.scala:134)
        at com.yotpo.metorikku.metric.MetricSet$$anonfun$run$1.apply(MetricSet.scala:50)
        at com.yotpo.metorikku.metric.MetricSet$$anonfun$run$1.apply(MetricSet.scala:45)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.yotpo.metorikku.metric.MetricSet.run(MetricSet.scala:45)
        at com.yotpo.metorikku.Metorikku$$anonfun$runMetrics$1.apply(Metorikku.scala:47)
        at com.yotpo.metorikku.Metorikku$$anonfun$runMetrics$1.apply(Metorikku.scala:45)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at com.yotpo.metorikku.Metorikku$.runMetrics(Metorikku.scala:45)
        at com.yotpo.metorikku.Metorikku$.delayedEndpoint$com$yotpo$metorikku$Metorikku$1(Metorikku.scala:19)
        at com.yotpo.metorikku.Metorikku$delayedInit$body.apply(Metorikku.scala:9)
        at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
        at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.App$$anonfun$main$1.apply(App.scala:76)
        at scala.collection.immutable.List.foreach(List.scala:392)
        at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
        at scala.App$class.main(App.scala:76)
        at com.yotpo.metorikku.Metorikku$.main(Metorikku.scala:9)
        at com.yotpo.metorikku.Metorikku.main(Metorikku.scala)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.spark.deploy.JavaMainApplication.start(SparkApplication.scala:52)
        at org.apache.spark.deploy.SparkSubmit.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:845)
        at org.apache.spark.deploy.SparkSubmit.doRunMain$1(SparkSubmit.scala:161)
        at org.apache.spark.deploy.SparkSubmit.submit(SparkSubmit.scala:184)
        at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:86)
        at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:920)
        at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:929)
        at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
```

some data does get sent to spline ui, but the spark job exits after the stack trace. i wonder if its related to having an inline query (ie `select 1 as col`) ie no `FROM TABLE...` or if due to one df going to multiple outputs

UPDATE:
confirmed due to queries with no FROM like -->
```sql
      SELECT
        'Green' AS data_quality_status,
        'Batch Started' AS batch_status,
        current_timestamp() AS run_timestamp,
        CAST(${batch_id} as bigint) AS batch_id
```

**Comment by wajda** [comment]
Will be fixed in AbsaOSS/spline#931
