### ISSUE TITLE
CreateDatabaseCommand not implemented error

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#319]
Spark **3.1.2**
Scala **2.12**
Job `DeltaDSV2Job`

Missing lineage for `dsv2.owbep`

```
21/10/06 15:24:14 ERROR LineageHarvester: 
****************************** OBJECT DUMP BEGIN ******************************
class org.apache.spark.sql.execution.command.CreateDatabaseCommand
  databaseName: java.lang.String = dsv2
  ifNotExists: boolean = false
  path: scala.Option Some
    x: java.lang.String = /tmp/6189388008103062383
  comment: scala.Option = None
  props: scala.collection.immutable.Map = Map()
  metrics: scala.collection.immutable.Map = null
  bitmap$0: boolean = false
****************************** OBJECT DUMP END   ******************************

21/10/06 15:24:14 ERROR SplineQueryExecutionListener: Unexpected error occurred during lineage processing for application: DeltaDSV2Job #local-1633526649205
za.co.absa.spline.harvester.exception.UnsupportedSparkCommandException: Spark command was intercepted, but is not yet implemented! Command:'class org.apache.spark.sql.execution.command.CreateDatabaseCommand'
	at za.co.absa.spline.harvester.builder.write.PluggableWriteCommandExtractor$.za$co$absa$spline$harvester$builder$write$PluggableWriteCommandExtractor$$alertWhenUnimplementedCommand(PluggableWriteCommandExtractor.scala:74)
	at za.co.absa.spline.harvester.builder.write.PluggableWriteCommandExtractor.asWriteCommand(PluggableWriteCommandExtractor.scala:46)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$tryExtractWriteCommand$1(LineageHarvester.scala:140)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.spline.harvester.LineageHarvester.tryExtractWriteCommand(LineageHarvester.scala:140)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1381)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

**Comment by cerveada** [comment]
First of all `CreateDatabaseCommand` is not really implemented, that command is currently ignored by Spline. So that error is expected and not a bug. (Maybe it should be just warning?)

The problem was that lineage for DeltaDSV2Job`s dsv2.owbep write was not created.

Unfortunately for me it works on
Spark 3.1.2
Scala 2.12
Java 8.0.265-amzn and 11.0.8-amzn

**Comment by cerveada** [comment]
Cannot reproduce
