### ISSUE TITLE
Cannot perform operation after producer has been closed

### ISSUE THREAD

**Issue by ChopperChen** [AbsaOSS/spline-spark-agent#383]
I build a spark job that copy data from a hive table to another table using agent-core_2.12-0.7.2.jar.Job is success,but spark log contains 'Caused by: java.lang.IllegalStateException: Cannot perform operation after producer has been closed'.
My code :
```
sparkConf
  .set("spline.mode", "REQUIRED")
  .set("spline.lineageDispatcher", "kafka")
  .set("spline.lineageDispatcher.kafka.topic", "data-topic")
  .set("spline.lineageDispatcher.kafka.producer.bootstrap.servers", "ip:9092")
val spark = SparkSession.builder().config(sparkConf).enableHiveSupport().getOrCreate()
SparkLineageInitializer.enableLineageTracking(spark)
```
Did I take some mistakes?

**Comment by cerveada** [comment]
- Can you share the whole error message?
- Was anything send to kafka's data-topic?

**Comment by ChopperChen** [comment]
the whole error message:
```
java.lang.RuntimeException: Cannot send lineage data to kafka topic data-topic
    at za.co.absa.spline.harvester.dispatcher.KafkaLineageDispatcher.sendRecord(KafkaLineageDispatcher.scala:91)
    at za.co.absa.spline.harvester.dispatcher.KafkaLineageDispatcher.send(KafkaLineageDispatcher.scala:69)
    at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$2(QueryExecutionEventHandler.scala:45)
    at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$2$adapted(QueryExecutionEventHandler.scala:43)
    at scala.Option.foreach(Option.scala:407)
    at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:43)
    at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
    at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
    at scala.Option.foreach(Option.scala:407)
    at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
    at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
    at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
    at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:153)
    at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:127)
    at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:115)
    at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:99)
    at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:127)
    at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:133)
    at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:82)
    at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
    at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
    at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
    at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:115)
    at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:99)
    at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
    at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
    at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
    at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
    at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
    at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
    at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1319)
    at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: java.lang.IllegalStateException: Cannot perform operation after producer has been closed
    at org.apache.kafka.clients.producer.KafkaProducer.throwIfProducerClosed(KafkaProducer.java:872)
    at org.apache.kafka.clients.producer.KafkaProducer.doSend(KafkaProducer.java:881)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:865)
    at org.apache.kafka.clients.producer.KafkaProducer.send(KafkaProducer.java:752)
    at za.co.absa.spline.harvester.dispatcher.KafkaLineageDispatcher.sendRecord(KafkaLineageDispatcher.scala:88)
    ... 31 more
```
@cerveada 
nothing is send to kafka.

**Comment by ChopperChen** [comment]
I think that producer was close by _za.co.absa.spline.harvester.dispatcher.KafkaLineageDispatcher.scala:51_.
spark executor exit and shut down kafka's producer.

**Comment by cerveada** [comment]
Yes, most likely. The lineage capturing code used to be called in the same thread in the older versions of spark. Now it's on a different one, so that is probably the cause, or one of them.

Which version of Spark were you using?

**Comment by ChopperChen** [comment]
The version of spark is 3.0.1，version of spline-spark-agent is 0.7.2.
