### ISSUE TITLE
HTTP Dispatcher :: Cannot send lineage data / Async timeout

### ISSUE THREAD

**Issue by wajda** [AbsaOSS/spline-spark-agent#417]
The `spline.lineageDispatcher.http.timeout.read` property value isn't propagated to the server causing the server async timeout to fire earlier causing 500 error.

```
22/03/18 22:58:31 WARN CompositeLineageDispatcher: Proceeding after an error occurred in an underlying dispatcher: za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher
java.lang.RuntimeException: Cannot send lineage data to http://localhost:8080/producer/execution-plans. HTTP Response: 500 {"errorId":"014c06e9-bd4a-42be-8959-bdb429dd4f27","timestamp":1647640711246,"message":null}
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.za$co$absa$spline$harvester$dispatcher$HttpLineageDispatcher$$sendJson(HttpLineageDispatcher.scala:87)
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$send$1.apply(HttpLineageDispatcher.scala:62)
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher$$anonfun$send$1.apply(HttpLineageDispatcher.scala:61)
	at scala.Option.foreach(Option.scala:257)
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.send(HttpLineageDispatcher.scala:61)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher$$anonfun$send$1.apply(CompositeLineageDispatcher.scala:39)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher$$anonfun$send$1.apply(CompositeLineageDispatcher.scala:39)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher$$anonfun$withErrorHandling$1.apply(CompositeLineageDispatcher.scala:51)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher$$anonfun$withErrorHandling$1.apply(CompositeLineageDispatcher.scala:50)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher.delegate(CompositeLineageDispatcher.scala:47)
	at za.co.absa.spline.harvester.dispatcher.CompositeLineageDispatcher.send(CompositeLineageDispatcher.scala:38)
	at za.co.absa.spline.agent.SplineAgent$$anon$2$$anonfun$handle$1$$anonfun$apply$mcV$sp$1.apply(SplineAgent.scala:87)
	at za.co.absa.spline.agent.SplineAgent$$anon$2$$anonfun$handle$1$$anonfun$apply$mcV$sp$1.apply(SplineAgent.scala:85)
	at scala.Option.foreach(Option.scala:257)
	at za.co.absa.spline.agent.SplineAgent$$anon$2$$anonfun$handle$1.apply$mcV$sp(SplineAgent.scala:85)
	at za.co.absa.spline.agent.SplineAgent$$anon$2.withErrorHandling(SplineAgent.scala:93)
	at za.co.absa.spline.agent.SplineAgent$$anon$2.handle(SplineAgent.scala:65)
	at za.co.absa.spline.harvester.listener.QueryExecutionListenerDelegate.onSuccess(QueryExecutionListenerDelegate.scala:28)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:124)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1$$anonfun$apply$mcV$sp$1.apply(QueryExecutionListener.scala:123)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:145)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling$1.apply(QueryExecutionListener.scala:143)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:45)
	at org.apache.spark.sql.util.ExecutionListenerManager.org$apache$spark$sql$util$ExecutionListenerManager$$withErrorHandling(QueryExecutionListener.scala:143)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply$mcV$sp(QueryExecutionListener.scala:123)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:123)
	at org.apache.spark.sql.util.ExecutionListenerManager$$anonfun$onSuccess$1.apply(QueryExecutionListener.scala:123)
	at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:156)
	at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:122)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:678)
	at org.apache.spark.sql.DataFrameWriter.saveToV1Source(DataFrameWriter.scala:285)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:271)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:229)
	at org.apache.spark.sql.DataFrameWriter.parquet(DataFrameWriter.scala:566)
	at za.co.absa.spline.example.batch.UnionJob$.delayedEndpoint$za$co$absa$spline$example$batch$UnionJob$1(UnionJob.scala:36)
	at za.co.absa.spline.example.batch.UnionJob$delayedInit$body.apply(UnionJob.scala:22)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at za.co.absa.spline.SparkApp.main(SparkApp.scala:27)
	at za.co.absa.spline.example.batch.UnionJob.main(UnionJob.scala)

```

**Comment by wajda** [comment]
related to  AbsaOSS/spline#485
