### ISSUE TITLE
0.7.6 version not working on databricks

### ISSUE THREAD

**Issue by JeremyDel** [AbsaOSS/spline-spark-agent#423]
Hey, 

We've been using spline on our Databricks platform( runtime 9.1 LTS with spark 3.1.2 and scala 2.12) since last year and we recently switched to one of the latest databricks runtime with spark 3.2 because we saw that you released the new 0.7.6 release that supports spark 3.2. 

When initialising there seems to be no issue, but when we launch a function that contains a merge operation, spark crashes and we see the following: The spark context has stopped and the driver is restarting. 

Checking the logs we see the following error:

```
22/04/22 09:56:26 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/Manifest;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:29)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:55)
	at za.co.absa.spline.harvester.ComposableIdGenerator.$anonfun$nextId$2(idGenerators.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at za.co.absa.spline.harvester.ComposableIdGenerator.nextId(idGenerators.scala:52)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:41)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:45)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1589)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/04/22 09:56:26 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-shared
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/Manifest;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:29)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:55)
	at za.co.absa.spline.harvester.ComposableIdGenerator.$anonfun$nextId$2(idGenerators.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at za.co.absa.spline.harvester.ComposableIdGenerator.nextId(idGenerators.scala:52)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:41)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:45)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1589)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/04/22 09:56:26 ERROR DatabricksMain$DBUncaughtExceptionHandler: Uncaught exception in thread spark-listener-group-shared!
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/Manifest;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:29)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$03d52d9f896243b7acb5f1938c1bbc13.__wrapper$1$03d52d9f896243b7acb5f1938c1bbc13$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:55)
	at za.co.absa.spline.harvester.ComposableIdGenerator.$anonfun$nextId$2(idGenerators.scala:52)
	at scala.Function1.$anonfun$andThen$1(Function1.scala:57)
	at za.co.absa.spline.harvester.ComposableIdGenerator.nextId(idGenerators.scala:52)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:41)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:45)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:85)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.immutable.List.map(List.scala:293)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:158)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:128)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:128)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:140)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1589)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/04/22 09:56:26 INFO HiveServer2: Shutting down HiveServer2
22/04/22 09:56:26 INFO ThriftCLIService: Caught InterruptedException. Shutting down thrift server.
22/04/22 09:56:26 INFO AbstractConnector: Stopped ServerConnector@48ba37dc{SSL, (ssl, http/1.1)}{0.0.0.0:10000}
22/04/22 09:56:26 INFO session: node0 Stopped scavenging
22/04/22 09:56:26 INFO AbstractConnector: Stopped Spark@1ee40b5c{SSL, (ssl, http/1.1)}{10.8.6.71:48740}
22/04/22 09:56:26 INFO AbstractConnector: Stopped HttpsRedirect@6885ed19{HTTP/1.1, (http/1.1)}{10.8.6.71:48340}
22/04/22 09:56:26 INFO ContextHandler: Stopped o.e.j.s.ServletContextHandler@5114c8a1{/,null,STOPPED}
22/04/22 09:56:26 INFO ThriftCLIService: Thrift HTTP server has been stopped
22/04/22 09:56:26 INFO SparkUI: Stopped Spark web UI at https://10.8.6.71:48740
22/04/22 09:56:26 INFO AbstractService: Service:ThriftHttpCLIService is stopped.
22/04/22 09:56:26 INFO AbstractService: Service:OperationManager is stopped.
22/04/22 09:56:26 INFO AbstractService: Service:SessionManager is stopped.
22/04/22 09:56:26 INFO AbstractService: Service:CLIService is stopped.
22/04/22 09:56:26 INFO AbstractService: Service:HiveServer2 is stopped.
22/04/22 09:56:26 INFO StandaloneSchedulerBackend: Shutting down all executors
22/04/22 09:56:26 INFO CoarseGrainedSchedulerBackend$DriverEndpoint: Asking each executor to shut down
22/04/22 09:56:26 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
22/04/22 09:56:26 INFO MemoryStore: MemoryStore cleared
22/04/22 09:56:26 INFO BlockManager: BlockManager stopped
22/04/22 09:56:26 INFO BlockManagerMaster: BlockManagerMaster stopped
22/04/22 09:56:26 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
22/04/22 09:56:27 INFO SparkContext: Successfully stopped SparkContext
22/04/22 09:56:29 INFO ClusterLoadAvgHelper: Current cluster load: 0, Old Ema: 0.85, New Ema: 0.0 
22/04/22 09:59:15 WARN ScalaDriverWrapper: Spark is detected to be down
22/04/22 09:59:15 WARN ScalaDriverWrapper: Fatal exception (spark down) in ReplId-347e9-96363-0753a-e
com.databricks.backend.common.rpc.SparkStoppedException: Spark down: 
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:426)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:748)
```

I am seeing a "similar" [issue](https://github.com/AbsaOSS/spline-spark-agent/issues/128) here with a previous version, so i am guessing databricks integration is a bit more tricky... 

Thanks again for the tool, I hope you we can resolve this easily

**Comment by wajda** [comment]
The error is caused by incompatible version of `json4s-ext` embedded into the Spline bundle. For some (not quite clear to me) reason Spark bundles unstable Json4s that changes public API like crazy and happens to be binary incompatible in almost every Spark minor release. 
We must not specify version of any Json4s component project wide, and only do it in concrete Spark bundle POMs to always package correct version.
Will fix the build accordingly.

**Comment by wajda** [comment]
@JeremyDel try this JAR - https://teamcity.jetbrains.com/repository/download/OpenSourceProjects_AbsaOSS_SplineAgentSpark_AutoBuildSpark32scala212/3844696:id/bundle-3.2/target/spark-3.2-spline-agent-bundle_2.12-0.7.7-SNAPSHOT.jar
It should fix the issue. Please let us know if it doesn't.

**Comment by mariobarbosaTA** [comment]
Hi @wajda 

I have tried do an execution with the agent 0.7.8 with this command (Spark version is 3.2.1): 

```shell
spark-submit \
  --packages za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.7.8 \
  --conf spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener \
  --conf spark.spline.producer.url=http://<PUBLIC_IP>:8080/producer \ sparkProgram.py
```

But I got the same error. I was reviewing your publication "Issue #423 move json4s-exp dependency from the spline-core..." but I don't understand where this change should be applied. 

Can you pelase guide me a bit to get Spline be able to track the linage when reading and writing AWS S3 from spark 3.2.1? 

Thanks.

**Comment by wajda** [comment]
> --packages za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.7.8

For Spark 3.2.1 you need to use bundle spark-3.2-spline-agent-bundle

**Comment by NishchayAgarwal** [comment]
Hey @wajda 
Hope you are doing well

As we are using latest spline spark jar file and running on the Runtime Version 9.1 LTS, I am getting the same error Custom Serializer as above mentioned, 
Can you please help for the same. I am highly obliged to you

**Comment by wajda** [comment]
Just tried agent 0.7.12 on Databricks 9.1 LTS and it worked as expected.

![image](https://user-images.githubusercontent.com/795479/204527408-c5e34738-2283-49c2-a24b-681e4bb48850.png)

Make sure you are using compatible libraries. 9.1 runtime is based on Spark 3.1.2 so you need to use agent version built for Spark 3.1, e.g. `za.co.absa.spline.agent.spark:spark-3.1-spline-agent-bundle_2.12:0.7.12`
