### ISSUE TITLE
Spline integration with Spark 2.3

### ISSUE THREAD

**Issue by adcb6gt** [AbsaOSS/spline-spark-agent#430]
Hi
I'm following the steps for setting up spline as mentioned on the https://absaoss.github.io/spline/ (0.7 version).
Using following distributions:
Spark 2.3.0
Python 3.6.5

Have setup arrango db, spline server and spline ui successfully as per the instructions provided in documentation.
I'm now in process to test the setup by submitting a pyspark job for lineage.

Downloaded the spline-agent bundle jar and placed it under Spark's "jars" directory:
spark-2.3-spline-agent-bundle_2.11-0.7.7.jar

Now launching pyspark shell using below command:
```
pyspark \
	--conf spark.sql.queryExecutionListeners=za.co.absa.spline.harvester.listener.SplineQueryExecutionListener \
	--conf spark.spline.producer.url=http://localhost:8080/producer

```
But end up getting

```
Traceback (most recent call last):
  File "/spark-2.3.0-bin-hadoop2.7/python/pyspark/shell.py", line 45, in <module>
    spark = SparkSession.builder\
  File "/spark-2.3.0-bin-hadoop2.7/python/pyspark/sql/session.py", line 183, in getOrCreate
    session._jsparkSession.sessionState().conf().setConfString(key, value)
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/spark-2.3.0-bin-hadoop2.7/python/pyspark/sql/utils.py", line 79, in deco
    raise IllegalArgumentException(s.split(': ', 1)[1], stackTrace)
pyspark.sql.utils.IllegalArgumentException: "Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':"

```
As an alternative, I then tried simply launching the pyspark console without any conf parameters.
Once the shell comes up successfully, i tried the below command in console just to see if the spline-bundle jar is being referenced or not by Spark:
```
sc._jvm.za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(spark._jsparkSession)
```
On running above command, i end up getting:

```
2022-05-06 13:29:33 WARN  NativeCodeLoader:62 - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
ERROR:root:Exception while sending command.
Traceback (most recent call last):
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1062, in send_command
    raise Py4JNetworkError("Answer from Java side is empty")
py4j.protocol.Py4JNetworkError: Answer from Java side is empty

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 908, in send_command
    response = connection.send_command(command)
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1067, in send_command
    "Error while receiving", e, proto.ERROR_ON_RECEIVE)
py4j.protocol.Py4JNetworkError: Error while receiving
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/java_gateway.py", line 1160, in __call__
  File "/spark-2.3.0-bin-hadoop2.7/python/pyspark/sql/utils.py", line 63, in deco
    return f(*a, **kw)
  File "/spark-2.3.0-bin-hadoop2.7/python/lib/py4j-0.10.6-src.zip/py4j/protocol.py", line 328, in get_return_value
py4j.protocol.Py4JError: An error occurred while calling z:za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking
```
I can confirm that JAVA_HOME is correctly set on my machine.
```
echo $JAVA_HOME
/usr/lib/jvm/java
```
Appreciate if any pointers can be provided to fix this issue. Thanks !

**Comment by cerveada** [comment]
Could low memory be the problem?
https://stackoverflow.com/questions/37252809/apache-spark-py4jerror-answer-from-java-side-is-empty

**Comment by adcb6gt** [comment]
Why do I get the error:
pyspark.sql.utils.IllegalArgumentException: "Error while instantiating 'org.apache.spark.sql.hive.HiveSessionStateBuilder':"

**Comment by cerveada** [comment]
It's hard to tell from the python errors. It would help a lot to know the Java errors with their stack trace. Is there some spark log with the Java Exceptions?

**Comment by wajda** [comment]
Closing the ticket as there is no precise information about the error. 
If the issue persists or if you have more detailed logs don't hesitate to reopen the ticket.
