### ISSUE TITLE
spline is not capturing data  databricks

### ISSUE THREAD

**Issue by zacayd** [AbsaOSS/spline-spark-agent#573]
Hi
my env is:

9.1 LTS (includes Apache Spark 3.1.2, Scala 2.12) 
spline agent - spark 3.3 scala 2.12

i use databricks and made the follwing cahnges
on the cluster (in Bold are my changes)

```
spark.hadoop.fs.azure.account.key.dwhprdadls01.dfs.core.windows.net 8oEdHj+Ax/ZdA5CaAaJW9dyrdFIvMeK2qr2kS+jkbj5LsbVIVQ9KW1rb0+anKGR0h2oK4N03XKlDerk78LfDtA==
spark.cleaner.referenceTracking.cleanCheckpoints true
**spark.spline.lineageDispatcher http
spark.spline.lineageDispatcher.http.producer.url http://XX.XX.XX.XX:8080/producer
spark.spline.mode REQUIRED**
spark.hadoop.fs.azure.account.key.dgcuatods01.dfs.core.windows.net /LCbgW2NfGFoC9HlKF613moW8G5POjC/99IIhM4AVy+WUnk5FEZ+ESmh4Usm6eehTVsOGHiWX+vzE/IHq0UYTA==
spark.hadoop.fs.azure.account.key.dwhuatadls01.dfs.core.windows.net iqKIlI4hCNEGXvFRUzMxp++bwy2zJH60i8vRyg4t21TUb4VC4BaOF3IBAJsRNYXfYthvOQnnWxxc932KMVCQeQ==
spark.databricks.delta.preview.enabled true
```

On the head of the notebook i put
`sc._jvm.za.co.absa.spline.harvester.SparkLineageInitializer.enableLineageTracking(spark._jsparkssion)`
and run the notebook but didnt get data on the ArangoDB

does there are any logs that i can see what is the problems?
what are the steps on the way ? i.e- spark Agnet->spline...?

**Comment by cerveada** [comment]
Spline Agent uses the Databricks Spark Driver logs, so look there.
There should be a log when the agent is initialised. Also look for any errors or warnings from agent.

**Comment by wajda** [comment]
@zacayd I guess you are aware that sharing your unprotected IPs, Azure Account Keys and other secrets on public is not the best idea...

**Comment by zacayd** [comment]
Hi Alex 
I have attached logs from the Spark UI logs 
but cannot tell what the problem 
can you have a look and tell me if you see any issues?

[log4j-active.txt](https://github.com/AbsaOSS/spline-spark-agent/files/10419755/log4j-active.txt)
[stderr.txt](https://github.com/AbsaOSS/spline-spark-agent/files/10419757/stderr.txt)
[stdout.txt](https://github.com/AbsaOSS/spline-spark-agent/files/10419758/stdout.txt)

**Comment by cerveada** [comment]
Why do you use Spark Agent for Spark 3.3 when you are on Spark 3.1 ?

**Comment by zacayd** [comment]
Hi i have attached the logs from the last run
saw this error  
can you direct me please what it says?

```
3/01/17 19:49:23 INFO AsyncEventQueue: Proc
[log4j-active.log](https://github.com/AbsaOSS/spline-spark-agent/files/10442815/log4j-active.log)
[log4j-active.log](https://github.com/AbsaOSS/spline-spark-agent/files/10442818/log4j-active.log)
ess of event SparkListenerSQLExecutionEnd(345,1673984956476) by listener ExecutionListenerBus took 7.438555274s.
**23/01/17 19:49:23 ERROR Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/ClassTag;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:30)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)**
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.DataTypeIdGenerator.nextId(idGenerators.scala:83)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:39)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:43)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1599)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
23/01/17 19:49:23 ERROR Utils: throw uncaught fatal error in thread spark-listener-group-shared
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/ClassTag;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:30)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.DataTypeIdGenerator.nextId(idGenerators.scala:83)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:39)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:43)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1599)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
23/01/17 19:49:23 ERROR DatabricksMain$DBUncaughtExceptionHandler: Uncaught exception in thread spark-listener-group-shared!
java.lang.NoSuchMethodError: org.json4s.CustomSerializer.<init>(Lscala/Function1;Lscala/reflect/ClassTag;)V
	at org.json4s.ext.UUIDSerializer$.<init>(JavaTypesSerializers.scala:30)
	at org.json4s.ext.UUIDSerializer$.<clinit>(JavaTypesSerializers.scala)
	at org.json4s.ext.JavaTypesSerializers$.<init>(JavaTypesSerializers.scala:26)
	at org.json4s.ext.JavaTypesSerializers$.<clinit>(JavaTypesSerializers.scala)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats(JavaTypesSupport.scala:25)
	at za.co.absa.commons.json.format.JavaTypesSupport.formats$(JavaTypesSupport.scala:23)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.formats(<no source file>:2)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.<init>(AbstractJsonSerDe.scala:33)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson(AbstractJsonSerDe.scala:32)
	at za.co.absa.commons.json.AbstractJsonSerDe.EntityToJson$(AbstractJsonSerDe.scala:32)
	at __wrapper$1$cbd828c736434978be96a7607e04bade.__wrapper$1$cbd828c736434978be96a7607e04bade$$anon$1.EntityToJson(<no source file>:2)
	at za.co.absa.spline.harvester.HashBasedUUIDGenerator.nextId(idGenerators.scala:57)
	at za.co.absa.spline.harvester.DataTypeIdGenerator.nextId(idGenerators.scala:83)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:39)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.LineageHarvesterFactory$$anon$1.convert(LineageHarvesterFactory.scala:55)
	at za.co.absa.spline.harvester.converter.DataTypeConverter.convert(DataTypeConverter.scala:43)
	at za.co.absa.spline.harvester.converter.AttributeConverter.convert(AttributeConverter.scala:42)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.za$co$absa$commons$lang$CachingConverter$$super$convert(OperationNodeBuilder.scala:46)
	at za.co.absa.commons.lang.CachingConverter.$anonfun$convert$1(converters.scala:47)
	at scala.collection.mutable.MapLike.getOrElseUpdate(MapLike.scala:209)
	at scala.collection.mutable.MapLike.getOrElseUpdate$(MapLike.scala:206)
	at scala.collection.mutable.AbstractMap.getOrElseUpdate(Map.scala:82)
	at za.co.absa.commons.lang.CachingConverter.convert(converters.scala:47)
	at za.co.absa.commons.lang.CachingConverter.convert$(converters.scala:44)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder$$anon$1.convert(OperationNodeBuilder.scala:46)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.$anonfun$outputAttributes$1(OperationNodeBuilder.scala:76)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes(OperationNodeBuilder.scala:76)
	at za.co.absa.spline.harvester.builder.OperationNodeBuilder.outputAttributes$(OperationNodeBuilder.scala:75)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes$lzycompute(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.outputAttributes(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:43)
	at za.co.absa.spline.harvester.builder.read.ReadNodeBuilder.build(ReadNodeBuilder.scala:28)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$6(LineageHarvester.scala:71)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.immutable.List.map(List.scala:298)
	at za.co.absa.spline.harvester.LineageHarvester.$anonfun$harvest$4(LineageHarvester.scala:71)
	at scala.Option.flatMap(Option.scala:271)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:118)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:102)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1599)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
23/01/17 19:49:23 INFO HiveServer2: Shutting down HiveServer2
23/01/17 19:49:23 INFO ThriftCLIService: Caught InterruptedException. Shutting down thrift server.
23/01/17 19:49:23 INFO AbstractConnector: Stopped ServerConnector@761b9314{SSL, (ssl, http/1.1)}{0.0.0.0:10000}
23/01/17 19:49:23 INFO session: node0 Stopped scavenging
23/01/17 19:49:23 INFO ContextHandler: Stopped o.e.j.s.ServletContextHandler@7267006e{/,null,STOPPED}
23/01/17 19:49:23 INFO ThriftCLIService: Thrift HTTP server has been stopped
23/01/17 19:49:23 INFO AbstractService: Service:ThriftHttpCLIService is stopped.
23/01/17 19:49:23 INFO AbstractConnector: Stopped Spark@6ffd4c0d{HTTP/1.1, (http/1.1)}{172.19.78.197:40001}
23/01/17 19:49:23 INFO AbstractService: Service:OperationManager is stopped.
23/01/17 19:49:23 INFO SparkUI: Stopped Spark web UI at http://172.19.78.197:40001
23/01/17 19:49:23 INFO AbstractService: Service:SessionManager is stopped.
23/01/17 19:49:23 INFO AbstractService: Service:CLIService is stopped.
23/01/17 19:49:23 INFO AbstractService: Service:HiveServer2 is stopped.
23/01/17 19:49:24 INFO BlockManagerInfo: Removed broadcast_14_piece0 on 172.19.78.196:35301 in memory (size: 58.3 KiB, free: 4.4 GiB)
23/01/17 19:49:24 INFO BlockManagerInfo: Removed broadcast_6_piece0 on 172.19.78.196:35301 in memory (size: 58.3 KiB, free: 4.4 GiB)
23/01/17 19:49:24 INFO BlockManagerInfo: Removed broadcast_13_piece0 on 172.19.78.196:35301 in memory (size: 31.3 KiB, free: 4.4 GiB)
23/01/17
```

**Comment by cerveada** [comment]
Why do you use Spark Agent for Spark 3.3 when you are on Spark 3.1 ?

The versions should match, that is probably causing your issues.

**Comment by PedroDubas** [comment]
Hello, I use spline with Databricks, you need to use the spline library in the same spark version, I recommend you use the spline version for the 3.1 version (the same as the spark cluster)

Obs: I couldn't use spline 1.0.0 (latest), I'm using version 0.7.13 in all my clusters
spline agent- spark 3.1 scala 2.12 @ 0.7.13

**Comment by cerveada** [comment]
@PedroDubas 
Do you have any issues with 1.0.0 (latest)? If so please open a ticket for it.

What do you mean by *Obs*?
