### ISSUE TITLE
StackOverflowError: util.Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext

### ISSUE THREAD

**Issue by tiguanin** [AbsaOSS/spline-spark-agent#583]
Hi! Getting error when use numerous filtrations of input DataFrame. 

Spline enabling and after few minutes I got StackOverflowError.

Other pipelines tracking successfully

Spark: _3.2.1_
Scala: _2.12.17_
Spline agent bundle: _0.7.13 / 1.0.0 / 1.0.1_ (for all versions)

Running on clean server with Spark. Without DataBricks . With spline agent bundle only.

```
2023-01-26 12:32:49,162 ERROR util.Utils: uncaught error in thread spark-listener-group-shared, stopping SparkContext
java.lang.StackOverflowError
	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
	at scala.collection.immutable.Stream.$anonfun$$plus$plus$1(Stream.scala:372)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1173)
	at scala.collection.immutable.Stream$Cons.tail(Stream.scala:1163)
```

**Comment by cerveada** [comment]
Is this the whole Exception message? Are there any other exceptions from Spline? It could help to pinpoint what is causing  the StackOverflowError.

**Comment by wajda** [comment]
@tiguanin are you sure it has anything to do with Spline? The posted stack trace represents an infinite realization of a looped Scala `Stream` collection. I don't think we have anything like that in Spline.

**Comment by tiguanin** [comment]
@cerveada  @wajda Yes, this is whole Exception message. I'm trying to find out the details. But in my spark job I using GraphX library. 
Spark Jobs that use GraphX -  falls. Maybe this is the reason of exception. But if spline hook is disabled jobs finishing successfully

**Comment by wajda** [comment]
So can I close it as irrelevant?

**Comment by tiguanin** [comment]
Fixed by increasing `xss` to 4mb for Spark. Issue is closed. Thanks!
