### ISSUE TITLE
Spline fails to report lineage when plan contains Scala 2.12 lambda

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline-spark-agent#72]
Checked on spline agent 0.5.1 with Scala 2.12, Spark 2.4.5

Code uses Scala Dataframe/Dataset transformation including lambda expressions it fails with following error:

```
WARN ExecutionListenerManager: Error executing query execution listener
java.lang.AssertionError: assertion failed: no symbol could be loaded from class a.b.c.MyClass$$Lambda$4843/566774261 in package c with name MyClass$$Lambda$4843/566774261 and classloader sun.misc.Launcher$AppClassLoader@18b4aac2
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1061)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:130)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:50)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:46)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:128)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:231)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classSymbol(JavaMirrors.scala:68)
	at za.co.absa.commons.reflect.ReflectionUtils$ModuleClassSymbolExtractor$.unapply(ReflectionUtils.scala:33)
	at za.co.absa.spline.harvester.converter.ValueDecomposer$$anonfun$$nestedInanonfun$handler$2$1.applyOrElse(ValueDecomposer.scala:52)
	at za.co.absa.spline.harvester.converter.ValueDecomposer$$anonfun$$nestedInanonfun$handler$2$1.applyOrElse(ValueDecomposer.scala:44)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:38)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter$$anonfun$$nestedInanonfun$renderer$1$1.applyOrElse(OperationParamsConverter.scala:35)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter$$anonfun$$nestedInanonfun$renderer$1$1.applyOrElse(OperationParamsConverter.scala:35)
	at scala.PartialFunction$OrElse.apply(PartialFunction.scala:172)
	at za.co.absa.spline.harvester.converter.ValueDecomposer.$anonfun$recursion$1(ValueDecomposer.scala:39)
	at za.co.absa.spline.harvester.converter.OperationParamsConverter.$anonfun$convert$6(OperationParamsConverter.scala:59)
	at scala.collection.TraversableLike$WithFilter.$anonfun$map$2(TraversableLike.scala:827)
```

**Comment by DaimonPl** [comment]
@wajda I'll try to prepare example tomorrow but it happened in very typical job with Scala code with lambda, something like

```
case class MyCC(a: String, b: String)

val ds: Dataset[MyCC] = ...

ds.map(x => x.copy(a = "1"))
```

**Comment by wajda** [comment]
Thanks, we'll take a look.
Technically it's a bug, and is definitely should be fixed. But on the other hand, since a lambda is a black box for JVM runtime you will hardly get any usable lineage from that type of Spark code anyway. Using structured API is more beneficial from both Spline a Spark perspective. The more detailed logical plan your job produces, the better it can be optimized by Spark Catalyst, and the more detailed lineage you can get in Spline.

**Comment by DaimonPl** [comment]
Source to target (input table to output table) is enough for us, this part should work fine even with lambda expressions?

Regarding api and catalyst I'm fully aware - I've been working with every spark version since Spark 1.4 :) dataframe/dsl api is ok for simple data transformations but complex business logic is often easier to write/test/maintain with pure Scala code - UDFs are sometimes not enough :)

**Comment by wajda** [comment]
true :)

**Comment by wajda** [comment]
Looks like it's a slippery spot in Scala reflection - https://github.com/scala/bug/issues/11828
The only decent workaround that comes to my mind would be placing a guard condition to the `ModuleClassSymbolExtractor` to check that the class isn't synthetic before trying to get a symbol.

**Comment by DaimonPl** [comment]
@wajda ok so as i understand it's easily reproducible with any lambda in plan?

Lineage will work anyway with that workaround? I mean table/datasource lineage - I fully understand that with lambda expressions there's no way to have column lineage :)

If you have any fix in your mind and we can get it to some public snapshot repo I can test it - we are now checking spline with spark jobs - most of them use lambda expressions from time to time

**Comment by wajda** [comment]
Yes, that's correct.
With lambdas you can still get source to source and operation level lineage. You even will also get a partial attribute level lineage (in the next Spline 0.6 release). What will be missing however is the lambda structure itself, that will in turn affect precision of the attribute lineage at places when lambda occurs. For instance, in your example above Spline won't tell you that `ds1` is produced from `ds` by assigning 1 to "a", and "a" doesn't depend on anything but the constant. Instead it will only say that `ds1` is a result of applying expression `foo.bar.baz.$$Lambda$42@7856` to the `ds`, and any of 'ds1' attributes could potentially depend on any of 'ds' attributes.   

The exception is fixed in AbsaOSS/commons#24 and will be released when the PR is approved.
To test it you can build the Commons project and replace the JAR in the Spline agent bundle. No changes in the Spline source code is required.

**Comment by wajda** [comment]
Spline Agent v.0.5.2 is released.
@DaimonPl, could you please confirm that it works?

**Comment by DaimonPl** [comment]
Yep, I'm not getting this problem anymore

There's other problem, I'll create different issue
