### ISSUE TITLE
Failure to report lineage in some specific scenario

### ISSUE THREAD

**Issue by DaimonPl** [AbsaOSS/spline-spark-agent#86]
One of (about 20) tested jobs reports following error when reporting lineage:

```
Unexpected error occurred during lineage processing for application: my-job #application_1589792979576_344130

scala.MatchError: NullaryMethodType(RefinedType(ClassSymbol(<refinement>, owner=9, flags=0, info=104 ,None),List(TypeRefType(ThisType(java.lang),java.lang.Object,List()), TypeRefType(ThisType(scala.math),scala.math.Ordering,List(TypeRefType(ThisType(scala),scala.Double,List())))))) (of class org.json4s.scalap.scalasig.NullaryMethodType)
	at org.json4s.reflect.ScalaSigReader$.findArgTypeForField(ScalaSigReader.scala:147)
	at org.json4s.reflect.ScalaSigReader$.readField(ScalaSigReader.scala:49)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.$anonfun$fields$3(Reflector.scala:69)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.mutable.ResizableArray.foreach(ResizableArray.scala:62)
	at scala.collection.mutable.ResizableArray.foreach$(ResizableArray.scala:55)
	at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:49)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:68)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.fields(Reflector.scala:81)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.properties(Reflector.scala:85)
	at org.json4s.reflect.Reflector$ClassDescriptorBuilder.result(Reflector.scala:184)
	at org.json4s.reflect.Reflector$.createDescriptor(Reflector.scala:53)
	at org.json4s.reflect.Reflector$.$anonfun$describe$1(Reflector.scala:48)
	at org.json4s.reflect.package$Memo.apply(package.scala:36)
	at org.json4s.reflect.Reflector$.describe(Reflector.scala:48)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:118)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:189)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:164)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.addField$1(Extraction.scala:110)
	at org.json4s.Extraction$.decomposeObject$1(Extraction.scala:140)
	at org.json4s.Extraction$.internalDecomposeWithBuilder(Extraction.scala:228)
	at org.json4s.Extraction$.decomposeWithBuilder(Extraction.scala:64)
	at org.json4s.Extraction$.decompose(Extraction.scala:242)
	at za.co.absa.commons.json.AbstractJsonSerDe$EntityToJson.toJson(AbstractJsonSerDe.scala:35)
	at za.co.absa.spline.harvester.dispatcher.HttpLineageDispatcher.send(HttpLineageDispatcher.scala:168)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$1(QueryExecutionEventHandler.scala:43)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.$anonfun$onSuccess$1$adapted(QueryExecutionEventHandler.scala:41)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:41)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:42)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:51)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:42)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$onSuccess$2(QueryExecutionListener.scala:127)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$onSuccess$2$adapted(QueryExecutionListener.scala:126)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$withErrorHandling$1(QueryExecutionListener.scala:148)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$withErrorHandling$1$adapted(QueryExecutionListener.scala:146)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.generic.TraversableForwarder.foreach(TraversableForwarder.scala:38)
	at scala.collection.generic.TraversableForwarder.foreach$(TraversableForwarder.scala:38)
	at scala.collection.mutable.ListBuffer.foreach(ListBuffer.scala:47)
	at org.apache.spark.sql.util.ExecutionListenerManager.withErrorHandling(QueryExecutionListener.scala:146)
	at org.apache.spark.sql.util.ExecutionListenerManager.$anonfun$onSuccess$1(QueryExecutionListener.scala:126)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at org.apache.spark.sql.util.ExecutionListenerManager.readLock(QueryExecutionListener.scala:159)
	at org.apache.spark.sql.util.ExecutionListenerManager.onSuccess(QueryExecutionListener.scala:126)
	at org.apache.spark.sql.DataFrameWriter.runCommand(DataFrameWriter.scala:678)
	at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:340)
	at org.apache.spark.sql.DataFrameWriter.insertInto(DataFrameWriter.scala:320)
(***)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.yarn.ApplicationMaster$$anon$2.run(ApplicationMaster.scala:685)
```

**Comment by wajda** [comment]
I'm struggling to understand what's happening here. It looks like a _json4s_ bug, but what triggers it?
What do you by saying that it's related to `org.apache.spark.sql.types.Metadata`
Is it trying to serialize something that isn't supposed to be serialized?
Can you reproduce it locally?

**Comment by wajda** [comment]
What branch didn't you encounter it on? Have you tried latest _relese/0.5_ ?

**Comment by DaimonPl** [comment]
I was using your branch with additional http logs

Yes I was able to reproduce it locally (we have e2e tests for each job using local spark context)

I used debugger and json4s fails when it encounters 'private final scala.collection.immutable.Map org.apache.spark.sql.types.Metadata.map'
on field named 'id' in that schema I sent you - looks like each spark datatype extends base type with 'metadata' field and in case of this schema it somehow fails with json4s

It looks that it happens because 'CatalogTable' is included in lineage data and in case of this schema it fails with json4s

I can try to prepare spline test but not not sure yet what's the root case (whole jobi quite big)

**Comment by wajda** [comment]
Aha, serializing a Spark type seems to be wrong already. Can you find what lineage property holds a `CatalogTable` instance?

**Comment by DaimonPl** [comment]
Not sue if this is helpful (partial lineage toString)

```
ExecutionPlan(e3d2a3f4-2f10-49f0-bf42-466f9fc0cc5f,Operations(WriteOperation(file:/var/folders/65/bbs2_cvx013ch2ctqg_r7b9hrndg49/T/spark_integration_test1394693823876114909/tmp/warehouse/retba_integration.db/tree_to_tree,None,false,0,List(1),Some(Map(table -> CatalogTable(
Database: retba_integration
Table: tree_to_tree
Owner: damian
Created Time: Sat May 30 13:53:26 CEST 2020
Last Access: Thu Jan 01 01:00:00 CET 1970
Created By: Spark 2.2 or prior
Type: EXTERNAL
Provider: hive
Table Properties: [last_modified_time=1590839613, transient_lastDdlTime=1590839613, last_modified_by=damian]
Location: file:/var/folders/65/bbs2_cvx013ch2ctqg_r7b9hrndg49/T/spark_integration_test1394693823876114909/tmp/warehouse/retba_integration.db/tree_to_tree
Serde Library: org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe
InputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat
OutputFormat: org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat
Storage Properties: [serialization.format=1]
Partition Provider: Catalog
Partition Columns: [`v_date`]
Schema: root
 |-- source_category_path: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |-- target_category_path: array (nullable = true)
 |    |-- element: struct (containsNull = true)
 |    |    |-- id: string (nullable = true)
 |    |    |-- name: string (nullable = true)
 |-- matches: long (nullable = true)
 |-- source: string (nullable = true)
 |-- frequency: double (nullable = true)
 |-- v_date: string (nullable = true)
))),
```

**Comment by DaimonPl** [comment]
@wajda but just to be sure I've just rebuilt latest release/5.0 (0.5.3-SNAPSHOT) instead of your branch and it works just fine!

Any chance you had some changed/additional code on your branch regarding http logging?

**Comment by DaimonPl** [comment]
Works fine on latest release branch

**Comment by wajda** [comment]
Yep, that was it! That why asked to try on the latest release branch :) Cool!

**Comment by wajda** [comment]
Thanks for helping with this @DaimonPl
