### ISSUE TITLE
Throwing runtime exception for delta commands

### ISSUE THREAD

**Issue by uday1409** [AbsaOSS/spline-spark-agent#96]
##
Current spline is not supported for delta commands such as MergeInto, Update, Delete

##
I have added `io.delta` package with scope provided as databricks cluster by default has `io.delta` imported, and made changes to `WriteCommandExtractor.scala` file.

##
```scala
import org.apache.spark.sql.delta.commands._
```
and added below code to commandsToBeImplemented just to see if it throws custom exception when run in Required mode.

```scala
classOf[MergeIntoCommand]
```

##
But it throws following exception when I run an application

```
Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.delta.commands.MergeIntoCommand
```

I am trying to debug the issue but your support on this is highly appreciated.

**Comment by wajda** [comment]
It means that `io.delta:delta-core` library isn't actually provided by your Spark environment. Check your Spark setup and make sure the `delta-core` is there, and the version is 0.3.0+

**Comment by uday1409** [comment]
Thats correct. I further debugged the issue and found that databricks does not provide all functionalities from io.delta , and has inhouse support for delta commands.

If I try to import io.delta into databricks , we cannot basically run any delta job as it fails with datasource instantiation error as 2 delta modules are imported now.

The command, MergeIntoCommandEdge is a native command provided by databricks , and there is no such open source package available from databricks to import this without actually importing io.delta package. If I import io.delta, we cannot basically do anything on databricks cluster .

MergeIntoCommand is part of  com.databricks.sql.tranaction but this is not available anywhere to import.

We need to figure out a way to incorporate this class (MergeInto) without actually importing io.delta

**Comment by wajda** [comment]
That's why Spline agent is full of dirty reflection hacks :) We're living in wild water...

**Comment by uday1409** [comment]
Could you please share the graph model relationship and entity details. We will try to find a way to write Merge command directly to database and see if that works.

**Comment by wajda** [comment]
You can find Swagger definition for the protocol on the `$SPLINE_SERVER_URL/docs/producer.html`

`WriteCommandExtractor` is the right place for adding new commands to.
Basically all you need is to return an instance of `WriteCommand` class, the most important  properties of which are `sourceIdentifier` and `query`.

`query` is a Spark logical plan that this write command represents. Every write command holds it in some property.
`SourceIdentifier` denotes  the write destination. The particular URI format doesn't matter as long as it meets to conditions - it uniquely identifies the data source in the cluster and is consistent with URIs produced by other write/read command that write to (or read from) the same location. This is important for linking individual jobs' lineages into a higher-level end-to-end lineage.

**Comment by 97nitt** [comment]
@uday1409 any luck implementing a `MergeIntoCommand` that works on Databricks? Just ran into this same issue, and was about to embark on the same journey...

**Comment by 97nitt** [comment]
@cerveada looks like you added support for the Databricks `CreateDeltaTableCommand` [here](https://github.com/AbsaOSS/spline-spark-agent/issues/107). 

Looks like I'll need something similar for `com.databricks.sql.transaction.tahoe.commands.MergeIntoCommandEdge` to get lineage from `MERGE INTO` SparkSQL statements. I may take a crack at this, any guidance on how you got the logging you needed (and how to interpret it) to implement that extractor?

**Comment by cerveada** [comment]
How to log is described here https://github.com/AbsaOSS/spline-spark-agent/discussions/394 especially the last paragraph. You need a TRACE level for evrything under `za.co.absa.spline` package.

You should find the MergeIntoCommandEdge command in an OBJECT DUMP BEGIN log. This is a log of the class structure and fields, that should hopefully be enough to see the fields you need to extract the dataSource data without seeing the actual code.

For the implementation, check the PR for Databricks's CreateDeltaTableCommand
https://github.com/AbsaOSS/spline-spark-agent/pull/112/files

It might be enough to just add some code in `DatabricksPlugin` similar way it is done for CreateDeltaTableCommand.

**Comment by 97nitt** [comment]
Looks like the attempt to dump that command is failing:
```
22/02/28 21:01:36 TRACE LineageHarvester: Attempt to dump structure of class com.databricks.sql.transaction.tahoe.commands.MergeIntoCommandEdge failed
java.lang.ArrayIndexOutOfBoundsException: 0
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.$anonfun$objectToStringRec$3(ObjectStructureDumper.scala:97)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.objectToStringRec(ObjectStructureDumper.scala:92)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.dump(ObjectStructureDumper.scala:39)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.$anonfun$logObjectStructure$1(ObjectStructureLogging.scala:41)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logObjectStructure(ObjectStructureLogging.scala:41)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logTraceObjectStructure(ObjectStructureLogging.scala:28)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logTraceObjectStructure$(ObjectStructureLogging.scala:27)
	at za.co.absa.spline.harvester.LineageHarvester.logTraceObjectStructure(LineageHarvester.scala:46)
	at za.co.absa.spline.harvester.LineageHarvester.tryExtractWriteCommand(LineageHarvester.scala:149)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1562)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```
Will keep poking at this, but would greatly appreciate any suggestions that come to mind while I do...

**Comment by 97nitt** [comment]
Looks like a problem in `ReflectionUtils` translating the Databricks command class. 

I added a logging statement [here](https://github.com/AbsaOSS/spline-spark-agent/blob/release/0.7/core/src/main/scala/za/co/absa/spline/harvester/logging/ObjectStructureDumper.scala#L97) to log the offending exception (with no stack trace).

Resulting logging snippet below:
```
22/03/01 03:00:43 ERROR ObjectStructureDumper: Uh oh! Reflection error occurred!
scala.reflect.internal.Symbols$CyclicReference: illegal cyclic reference involving class InterfaceAudience
22/03/01 03:00:43 INFO LineageHarvester: Attempt to dump structure of class com.databricks.sql.transaction.tahoe.commands.MergeIntoCommandEdge failed
java.lang.ArrayIndexOutOfBoundsException: 0
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.$anonfun$objectToStringRec$3(ObjectStructureDumper.scala:100)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.objectToStringRec(ObjectStructureDumper.scala:93)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.dump(ObjectStructureDumper.scala:40)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.$anonfun$logObjectStructure$1(ObjectStructureLogging.scala:44)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logObjectStructure(ObjectStructureLogging.scala:44)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logInfoObjectStructure(ObjectStructureLogging.scala:28)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logInfoObjectStructure$(ObjectStructureLogging.scala:27)
	at za.co.absa.spline.harvester.LineageHarvester.logInfoObjectStructure(LineageHarvester.scala:46)
	at za.co.absa.spline.harvester.LineageHarvester.tryExtractWriteCommand(LineageHarvester.scala:149)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1562)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
22/03/01 03:00:43 INFO AsyncEventQueue: Process of event SparkListenerSQLExecutionEnd(21,1646103641776) by listener ExecutionListenerBus took 1.849244831s.
22/03/01 03:00:43 INFO LineageHarvester: class com.databricks.sql.transaction.tahoe.commands.MergeIntoCommandEdge was not recognized as a write-command. Skipping.
22/03/01 03:00:43 ERROR ObjectStructureDumper: Uh oh! Reflection error occurred!
java.lang.AssertionError: assertion failed: no symbol could be loaded from interface org.apache.hadoop.classification.InterfaceAudience$Public in class InterfaceAudience with name Public and classloader sun.misc.Launcher$AppClassLoader@1134affc
	at scala.reflect.internal.SymbolTable.throwAssertionError(SymbolTable.scala:184)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala1(JavaMirrors.scala:1061)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$classToScala$1(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.$anonfun$toScala$1(JavaMirrors.scala:130)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.$anonfun$toScala$1(TwoWayCaches.scala:50)
	at scala.reflect.runtime.TwoWayCaches$TwoWayCache.toScala(TwoWayCaches.scala:46)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.toScala(JavaMirrors.scala:128)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.classToScala(JavaMirrors.scala:1019)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy.<init>(JavaMirrors.scala:196)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:195)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaAnnotationProxy$.apply(JavaMirrors.scala:195)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$copyAnnotations(JavaMirrors.scala:717)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.load(JavaMirrors.scala:772)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$FromJavaClassCompleter.complete(JavaMirrors.scala:783)
	at scala.reflect.internal.Symbols$Symbol.info(Symbols.scala:1542)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.scala$reflect$runtime$SynchronizedSymbols$SynchronizedSymbol$$super$info(SynchronizedSymbols.scala:203)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.$anonfun$info$1(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info(SynchronizedSymbols.scala:149)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol.info$(SynchronizedSymbols.scala:158)
	at scala.reflect.runtime.SynchronizedSymbols$SynchronizedSymbol$$anon$7.info(SynchronizedSymbols.scala:203)
	at scala.reflect.internal.Symbols$Symbol.isDerivedValueClass(Symbols.scala:834)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$DerivedValueClassMetadata.<init>(JavaMirrors.scala:301)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaVanillaMethodMirror0.<init>(JavaMirrors.scala:394)
	at scala.reflect.runtime.JavaMirrors$JavaMirror.scala$reflect$runtime$JavaMirrors$JavaMirror$$mkMethodMirror(JavaMirrors.scala:356)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectMethod(JavaMirrors.scala:283)
	at scala.reflect.runtime.JavaMirrors$JavaMirror$JavaInstanceMirror.reflectMethod(JavaMirrors.scala:268)
	at za.co.absa.commons.reflect.ReflectionUtils$.$anonfun$extractFieldValue$5(ReflectionUtils.scala:143)
	at scala.Option.map(Option.scala:230)
	at za.co.absa.commons.reflect.ReflectionUtils$.reflectClass$1(ReflectionUtils.scala:141)
	at za.co.absa.commons.reflect.ReflectionUtils$.reflectClassHierarchy$1(ReflectionUtils.scala:112)
	at za.co.absa.commons.reflect.ReflectionUtils$.extractFieldValue(ReflectionUtils.scala:169)
	at za.co.absa.commons.reflect.ReflectionUtils$.extractFieldValue(ReflectionUtils.scala:184)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.$anonfun$dump$default$2$1(ObjectStructureDumper.scala:35)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.$anonfun$objectToStringRec$3(ObjectStructureDumper.scala:96)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:238)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:198)
	at scala.collection.TraversableLike.map(TraversableLike.scala:238)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:231)
	at scala.collection.mutable.ArrayOps$ofRef.map(ArrayOps.scala:198)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.objectToStringRec(ObjectStructureDumper.scala:93)
	at za.co.absa.spline.harvester.logging.ObjectStructureDumper$.dump(ObjectStructureDumper.scala:40)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.$anonfun$logObjectStructure$1(ObjectStructureLogging.scala:44)
	at scala.util.Try$.apply(Try.scala:213)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logObjectStructure(ObjectStructureLogging.scala:44)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logInfoObjectStructure(ObjectStructureLogging.scala:28)
	at za.co.absa.spline.harvester.logging.ObjectStructureLogging.logInfoObjectStructure$(ObjectStructureLogging.scala:27)
	at za.co.absa.spline.harvester.LineageHarvester.logInfoObjectStructure(LineageHarvester.scala:46)
	at za.co.absa.spline.harvester.LineageHarvester.tryExtractWriteCommand(LineageHarvester.scala:149)
	at za.co.absa.spline.harvester.LineageHarvester.harvest(LineageHarvester.scala:64)
	at za.co.absa.spline.harvester.QueryExecutionEventHandler.onSuccess(QueryExecutionEventHandler.scala:42)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$2$adapted(SplineQueryExecutionListener.scala:40)
	at scala.Option.foreach(Option.scala:407)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.$anonfun$onSuccess$1(SplineQueryExecutionListener.scala:40)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.withErrorHandling(SplineQueryExecutionListener.scala:49)
	at za.co.absa.spline.harvester.listener.SplineQueryExecutionListener.onSuccess(SplineQueryExecutionListener.scala:40)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:155)
	at org.apache.spark.sql.util.ExecutionListenerBus.doPostEvent(QueryExecutionListener.scala:131)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.sql.util.ExecutionListenerBus.postToAll(QueryExecutionListener.scala:131)
	at org.apache.spark.sql.util.ExecutionListenerBus.onOtherEvent(QueryExecutionListener.scala:135)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:102)
	at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
	at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:119)
	at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:103)
	at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
	at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
	at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
	at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1562)
	at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

**Comment by cerveada** [comment]
That try & catch is there to ignore errors like these, unfortunately it does not expect the stack trace to be empty.

If you replace the line 97 with this I think the ObjectStructureDumper should start working:
```Scala
                  case NonFatal(e) =>
                    val stackTrace = e.getStackTrace()
                    val stackTraceLog =
                      if (stackTrace != null && stackTrace.size > 0) s"at ${stackTrace(0)}"
                      else "(no stack trace available)"
                    s"! error occurred: ${e.getMessage} $stackTraceLog"
```

We will fix this ourselves, of course, but it might take some time to be released.

**Comment by 97nitt** [comment]
Thanks, @cerveada that makes sense. The suggested code change above took care of the `ArrayIndexOutOfBoundsException`, but I still wasn't seeing the object dump in the logs. Added some more debug logging, logging each `ObjectBox` created, and found the issue.  It appears this `MergeIntoCommandEdge` class is quite complex, this produced a _ton_ of logging. And it revealed that the object dump had entered an infinite loop, see the log snippet below:
```
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=200080614570384, fieldName=seed, fieldType=java.util.concurrent.atomic.AtomicLong, depth=6
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=0.0, fieldName=nextNextGaussian, fieldType=double, depth=6
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=false, fieldName=haveNextNextGaussian, fieldType=boolean, depth=6
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=200080614570384, fieldName=value, fieldType=long, depth=7
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=0.0, fieldName=value, fieldType=double, depth=7
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=0.0, fieldName=value, fieldType=double, depth=8
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=0.0, fieldName=value, fieldType=double, depth=9
22/03/01 12:04:06 DEBUG ObjectStructureDumper: ObjectBox: value=0.0, fieldName=value, fieldType=double, depth=10
```
And that pattern at the end just kept repeating at an incrementing depth.

Hoping I can sift through this logging and find the relevant bits to create an execution plan before this loop starts.

**Comment by cerveada** [comment]
I think this could be fixed by adding another condition in `isReadyForPrint` function. Like `value.isInstanceOf[java.lang.Number]`

**Comment by cerveada** [comment]
No, I was wrong, actually it seems to be some kind of Random object is the case, not AtomicLong. So maybe it would help to add that Random object to that condition. Looks like it's `java.util.Random`

As you can see, the ObjectStructureDumper is not perfect. It is trying to print some useful data about any existing object, but it is hard to find all edge cases like this. It's basically last resort when we can see the source code, like in DataBricks case.

**Comment by uday1409** [comment]
One important thing about MergeIntoCommand is that, the execution plan returned by the command does not contain all the dependent logical plan of source view or table used in merge (source view derivation may involve many transformations). It just gives target table , source view name and update statement if any. I may be wrong but this is what I get when I do .explain() on the merge command. Similar thing is observed for open source Delta too. Incontrast, create or write as delta table gives all the logical plan of transformations involved.

**Comment by 97nitt** [comment]
So I was able to see (via logging) the inputs/outputs of the Databricks merge command, but am now stuck figuring out how to get that data into an execution plan. I probably jumped into the deep end too quickly, with a limited understanding of the internals of Spark and Spline (and Scala). Probably can't justify spending much more time on this right now. Appreciate the help, I'll probably keep poking at this here and there until/unless someone with better Spark/Spline chops is motivated to take this on.

**Comment by uday1409** [comment]
@97nitt can you please share the logs related to input and output
